OpenShot/libopenshot

cmake/Windows/build-imagemagick.sh, cmake/Windows/urls.txt
I'm trying to build OpenShot for Windows following [your manual](https://docs.google.com/document/d/1V6nq-IuS9zxqO1-OSt8iTS_cw_HMCpsUNofHLYtUNjM/pub#h.3w3btur7l3ik).
It seems that https://github.com/OpenShot/libopenshot/tree/master/cmake/Windows contains old references that don't exist anymore.
It seems to me that I've been able to build ImageMagick with the files contained in this pull request.
=> Fix build ImageMagick under Windows

cmake/Modules/FindJsonCpp.cmake, include/Json.h, src/CMakeLists.txt, src/KeyFrame.cpp
This PR resolves #14 by enabling to build libopenshot with system installed libjsoncpp using CMake option `USE_SYSTEM_JSONCPP` (default OFF). If not set, embedded sources of libjsoncpp will be used as before.
As remarked [here](https://github.com/komackaj/libopenshot/commit/36af4edc23f2adf37e26e54edbb993ff0068dde4#commitcomment-16855054) there is an issue with `jsoncppConfig.cmake` distributed in `libjsoncpp-dev` on Debian, therefore we use custom CMake find module leveraging pkg-config if available and ignore CMake config files for jsoncpp.
It also fixes compilation ambiguity error when using libjsoncpp 0.6.0 and 1.6.5
=> Enable system jsoncpp

include/FrameMapper.h, src/FFmpegReader.cpp, src/FrameMapper.cpp, src/Timeline.cpp, tests/FrameMapper_Tests.cpp
Summary
Fixes audio sample distribution across different clips so that there are no extra or missing samples on final output frames which result in small audible clicks on output tracks
Details
a) Added a timeline_frame_offset member to FrameMapper which indicates the position of the clip relative to the main output Timeline. This allows the number of audio samples in each requested frame to match exactly what the Timeline needs.
b) Fixed logic in AudioLocation::is_near() to handle a specific case where consecutive frames can have varying audio samples_per_frame (which happens when the audio sample rate is not an integer multiple of the video frame rate), and the sample_start value is at that upper limit of samples_per_frame.
c) Fixed creation of Samples structure in FrameMapper::Init(). …
=> Audio fix 1

tests/CMakeLists.txt
This overrides TEST_MEDIA_PATH so that it is no longer set to
"../../src/examples/"
@jonoomph
=> Properly set test media files path, fixes #36

src/ZmqLogger.cpp
Reverts OpenShot/libopenshot#82, this is not cross-platform, and fails on older Mac builds
=> Revert "Prepend current time (hires) to messages logged via ZmqLogger"

.gitlab-ci.yml
The 2 mingw-make commands both compile everything... so I'm trying to only include 1 of them, to speed up compilation on build servers.
=> Experimental: remove additional make command

src/Clip.cpp
Make copy of time-mapped image data (transformed, passed to effects, etc...), to prevent flickering or crashes.
=> Make copy of time-mapped image data

include/Frame.h, include/FrameMapper.h, src/FFmpegReader.cpp, src/Frame.cpp, src/FrameMapper.cpp, src/Timeline.cpp
Fixing audio pops due to resampling (this fixes a bunch of audio popping-related bugs). Now Frame objects track their own max_audio_sample_count, as we add audio data... so we have an accurate bounds on each frame.
=> Fixing audio pops due to resampling

src/Frame.cpp
Sometimes a negative starting sample is passed into AddAudio, and we should not allow this.
=> Prevent a negative starting sample when adding audio to a frame

.gitlab-ci.yml
Adding conditional download of artifacts... use current branch name first, and then fallback to develop artifacts. This is to help the build pipeline support all branches.
=> Adding conditional download of artifacts

cmake/Modules/FindOpenShotAudio.cmake
Fix cmake module lookup for libopenshot-audio, to always try the ENV variable first
=> Fix cmake module lookup for libopenshot-audio

include/Clip.h, include/Enums.h, src/Clip.cpp, src/Timeline.cpp
Adding new audio mixing enum, to allow for no automatic audio mixing, average mixing (where all overlapping clips average to 100% audio), or reduce mixing (where clips overlapping clips are all reduced by a constant value to reduce popping).
=> Adding new audio mixing enum to customize audio mixing

include/FFmpegWriter.h, src/FFmpegWriter.cpp
Adding FFmpegWriter::IsValidCodec static function to check if any codec name is valid and installed on the user's system. This is needed for AAC support, since there are many encoder versions.
=> Adding FFmpegWriter::IsValidCodec static function

include/OpenMPUtilities.h, src/FFmpegReader.cpp, src/FFmpegWriter.cpp
Limiting threads for both FFmpeg and OpenMP, attempting to find a balance of parallel performance, while not spawning too many threads). Sometimes more is not always better.
=> Limiting threads for both FFmpeg and OpenMP

src/Timeline.cpp
Protect effects with critical (prevents crashing and freezing around transitions). Thanks Peter and Michael Sloan!
=> Protect effects with critical (prevents crashing and freezing around transitions)

include/Version.h
Official release of 0.2.2 of libopenshot. This release includes a last minute bug fix related to transition effect crashes that I want to include in openshot-qt 2.4.3 (the upcoming release).
=> Bumping version to 0.2.2 (SO: still 16)

src/Qt/PlayerPrivate.cpp, src/Qt/VideoCacheThread.cpp
Improving cache performance by preventing the cache from getting behind the currently displaying frame #. This will dramatically improve performance for certain types of playback scenarios. Before the cache could get behind, and would actually be requesting frames < 10 or 20 frames from the current location, which would case the Reader to Seek backwards for no reason, causing stops and pauses.
=> Improving cache performance by preventing the cache from getting behind

src/FFmpegReader.cpp, src/FFmpegWriter.cpp, src/Timeline.cpp
Often in a preview, **Scale: None** renders differently than on final render, due to optimizations in previews which reduce the image size. Now disabling scaling works correctly in both preview and final render.
=> Fixing Scale Mode (None) in previews

include/FFmpegReader.h, include/FFmpegWriter.h, include/OpenShot.h, include/Settings.h, include/ZmqLogger.h, src/CMakeLists.txt, src/FFmpegReader.cpp, src/FFmpegWriter.cpp, src/Settings.cpp, src/bindings/python/openshot.i, src/bindings/ruby/openshot.i, tests/CMakeLists.txt, tests/Settings_Tests.cpp
New Settings Class to be used for changing realtime settings used by libopenshot, such as scaling mode for preview vs final render, or hardware decode, etc... This replaces a clunky environment variable approach, which required a restart of OpenShot. This new Settings class will be easy to extend, and high performance, and no longer requires a restart when settings change.
=> New Settings Class to be used for changing realtime settings used by libopenshot

.gitlab-ci.yml, cmake/Modules/FindRESVG.cmake, include/ChunkReader.h, include/Clip.h, include/ClipBase.h, include/FFmpegReader.h, include/FFmpegUtilities.h, include/QtImageReader.h, include/ReaderBase.h, include/Settings.h, include/Timeline.h, src/CMakeLists.txt, src/ChunkReader.cpp, src/Clip.cpp, src/FFmpegReader.cpp, src/FrameMapper.cpp, src/QtImageReader.cpp, src/ReaderBase.cpp, src/Settings.cpp, src/Timeline.cpp, tests/CMakeLists.txt
* Integration of resvg library (https://github.com/RazrFalcon/resvg/) for much improved SVG rendering features (compared to the Tiny 1.2 Specification in Qt). Fallback to Qt if resvg is not found during build.
* Major refactor of max_width and max_height for preview optimization
* Fixed many bugs related to preview resizing, with regards to cached frames
* Based on a previous PR: https://github.com/OpenShot/libopenshot/pull/143
* Special thanks to @N3WWN, @ferdnyc, and @RazrFalcon! 
It will take a while for resvg to be packaged in the various Linux distros. It is a rust library, and uses cargo for it's build process. I was unable to include the package in our PPA due to the dependency on cargo (and GitHub is internally used, which is forbidden on LaunchPad's build servers). The Debian …
=> Integration of resvg SVG library (optional during build)

cmake/Modules/FindRESVG.cmake, src/CMakeLists.txt, tests/CMakeLists.txt
`find_package_handle_standard_args` is supposed to set the `_FOUND` variable automatically (as the comment right above it says), as well as handling things like `REQUIRED`, `QUIETLY`, etc. It should always be run at the end of a module, for this reason.
This change removes the conditionals around the call, lets it handle what it's meant to handle, and defines a custom failure message for discovery that replaces the manual one in `src/CMakeList.txt`.
In addition, the `REQUIRED` is removed from `tests/CMakeLists.txt`, since it's _supposed_ to mark the module as required (which ReSVG is not), and was only working due to the aforementioned improper
conditional wrapping of the module's cleanup.
With these changes, on my system libopenshot still builds and `make test` still runs successfully …
=> Some polishing for the cmake ReSVG discovery

src/FFmpegWriter.cpp
Set video bit rate to 0 if an invalid bit rate detected, which happens when using CRF.
=> Set video bit rate to 0 if an invalid bit rate detected

include/Timeline.h, src/FFmpegReader.cpp
MP3 files are unique, in that they typically contain a single video frame, and then the rest of the data is audio frames. So, I've added a condition to better support that, so OpenShot doesn't spend forever looking for missing video frames. Also, I've refactored the missing frame logic to better handle audio data and video data which is missing (I've separated the logic), and all my broken test files work great now!
=> MP3 Special Handling & Missing Frame Refactor

include/Clip.h, include/Coordinate.h, src/Clip.cpp, src/Coordinate.cpp, src/FrameMapper.cpp, src/KeyFrame.cpp, tests/KeyFrame_Tests.cpp
I've done some heavy refactoring to our Keyframes and Framemapper, to allow for faster loading of OpenShot projects, and deferring some of the actual Keyframe number crunching until absolutely needed. Also, the Keyframes are magnitudes faster now, since I've removed some horribly inefficient looping calculating... especially for long clips which require hundreds of thousands of coordinates in those Keyframes.
This also touches how time mapping works a little bit, and there are still some issues with respects to the time mapping feature... audio crackles and audio dead spots... but those bugs already existed, and continue to exist after this refactor.
=> Improved Keyframe Performance

src/FFmpegWriter.cpp, src/Timeline.cpp
When calling Timeline::SetMaxSize, it should never allow a size larger than the timeline's size, which solves broken previews for very small resolutions. Also, the q settings were incorrect when exporting a "low quality" CRF of 50 (this caused an exception before).
=> Invalid SetMaxSize Logic and Invalid CRF q settings in FFmpegWriter

cmake/Modules/FindOpenShotAudio.cmake, include/AudioBufferSource.h, include/AudioReaderSource.h, include/AudioResampler.h, include/Clip.h, include/Frame.h, include/Settings.h, include/ZmqLogger.h
Adjustments to build libopenshot against a libopenshot-audio built with the new Juce 5.4.3 changes from my companion PR OpenShot/libopenshot-audio#37.
* All header files (7) which contained `#include "JuceLibraryCode/JuceHeader.h"` were changed to simply `#include "JuceHeader.h"`, which works in concert with the new include dir layout for libopenshot-audio.
* Savaged the `cmake/Modules/FindOpenShotAudio.cmake` discovery code to remove all of the recursive header-file discovery and `LIBOPENSHOT_AUDIO_BASE_DIR` noise. 
Now it simply looks for the file `JuceHeader.h` and considers that location to be the `LIBOPENSHOT_AUDIO_INCLUDE_DIR`, which it is. So much simpler it's not even funny.
(Note: **DO NOT MERGE** until after the corresponding changes to libopenshot-audio are committed. See …
=> Juce 5 changes

.gitlab-ci.yml, .travis.yml, cmake/Modules/FindOpenShotAudio.cmake, include/AudioBufferSource.h, include/AudioReaderSource.h, include/AudioResampler.h, include/Clip.h, include/EffectBase.h, include/Frame.h, include/Qt/AudioPlaybackThread.h, include/QtPlayer.h, include/Settings.h, include/ZmqLogger.h, src/Frame.cpp, src/Qt/AudioPlaybackThread.cpp, src/QtPlayer.cpp
Some header path changes to libopenshot based on the new JUCE 5 refactor in libopenshot-audio. Also, adding some error persistence when initializing JUCE DeviceManager (if an error occurs, such as a WASAPI Windows error, where the playback and recording device have different sample rates, etc...)
=> Upgrade to JUCE 5

CMakeLists.txt, cmake/Modules/UseDoxygen.cmake, src/bindings/python/CMakeLists.txt, src/bindings/python/CMakeLists.txt~, src/bindings/ruby/CMakeLists.txt, src/bindings/ruby/CMakeLists.txt~, tests/CMakeLists.txt
Like the libopenshot changes, mostly enhancements to use CMake 3.1+ features
- Enforce the minimum CMake version, and set 3.14 as max tested (as it's what I'm using)
(Using CMake > 3.14 won't fail, instead it'll automatically set compatibility options for new 3.14+ features)
- Update Doxygen module, as (implicitly) removing 2.x compatibility options breaks it
- Configure for C++11 standard in the recommended CMake manner
However, this also contains critical fixes to the `CMakeLists.txt` files for the bindings, which currently will not build under very recent CMake versions, since `SWIG_ADD_MODULE()` is completely deprecated. However, since its replacement `swig_add_library()` didn't even exist until CMake 3.8, that logic is conditionalized e.g.:
```cmake
if (CMAKE_VERSION VERSION_LESS …
```
=> Cmake 3.1+ project updates (and 3.12+ SWIG build fixes)

.gitlab-ci.yml
Fixing python install logic for GitLab (since we've changed the prefix of where it's installed). On older builds, the Python bindings were installed into `/usr/local/`, but now they are correctly installed into our `build/install-x64` path.
=> Fixing python install logic for GitLab

src/bindings/python/CMakeLists.txt, src/bindings/ruby/CMakeLists.txt
I somehow missed that `if(POLICY CMPxxxx)` exists to wrap `cmp_policy()` calls so that only CMake versions that understand a policy attempt to set it. Which is way smarter than the version-based logic I was using.
=> Use if(POLICY)

src/CMakeLists.txt
The JsonCPP discovery previously claimed it "Could NOT find" the system JsonCPP, even when it never checked because `USE_SYSTEM_JSONCPP` was not enabled.
With this change it correctly reports whether it's looking for the system install or just using the built-in copy. For convenience, the message includes the name of the option that controls this behavior.
=> Fix up JsonCPP discovery messages

tests/CMakeLists.txt
By specifying `COMMAND openshot-test` for the custom target,
the path to the compiled executable is automatically used
and the openshot-test target is automatically made a dependency.
=> Make os_test use openshot-test target

src/bindings/python/CMakeLists.txt
Reverts OpenShot/libopenshot#222
This broke on both Linux and Mac GitLab builders... so just reverting for now.
Linux Output:
```
-- Removed runtime path from "/home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/install-x64/../../../../../../../../../usr/local/lib/python3.4/dist-packages/_openshot.so"
-- Installing: /home/gitlab-runner/builds/5cd61c66/0/OpenShot/libopenshot/build/install-x64/../../../../../../../../../usr/local/lib/python3.4/dist-packages/openshot.py
$ mv install-x64/lib/python3.4/site-packages/*openshot* install-x64/python
mv: cannot stat ‘install-x64/lib/python3.4/site-packages/*openshot*’: No such file or directory
ERROR: Job failed: exit status 1
```
Mac Output:
```
-- Installing: /Users/jonathan/builds/7d5103a1/0/OpenShot/libopenshot/build/install-x64/../ …
```
=> Revert "Update Python install path detection"

src/KeyFrame.cpp
Remove else so that the default return value is used if no other return was used."else if" in line 334 had no else and therefore in some cases no return value was present.
=> The default return value is present

include/QtImageReader.h, src/QtImageReader.cpp
The commit has the wrong description (on accident), but this fixes certain cases where large images would be constantly resized from the original, causing laggy and horrible performance, especially on large JPG or bitmaps.
=> Improve QtImageReader caching logic (fixes performance of larger static images)

include/CacheBase.h, include/CacheMemory.h, include/Clip.h, include/ClipBase.h, include/DummyReader.h, include/FFmpegReader.h, include/FFmpegUtilities.h, include/Frame.h, include/FrameMapper.h, include/QtImageReader.h, include/ReaderBase.h, include/Timeline.h, src/CacheBase.cpp, src/Clip.cpp, src/ClipBase.cpp, src/DummyReader.cpp, src/FFmpegReader.cpp, src/FFmpegWriter.cpp, src/Frame.cpp, src/FrameMapper.cpp, src/QtImageReader.cpp, src/ReaderBase.cpp, src/Timeline.cpp
- some were with libav functions
- same were due to non-virtual destructors
it was previously leaking a full frame (could be several megs based on resolution) plus a bunch of libav structures. Most of the fixes were found using -fsanitize=address on a very simple test program (setting the environment variable ASAN_OPTIONS=fast_unwind_on_malloc=0 when running the program generates much more helpful stack traces too). Tested only with ffmpeg 3.2.
=> fix a number of memory leaks

src/FFmpegReader.cpp
When a packet wasn't found, the allocated next_packet was leaked
=> plug another small leak

src/FrameMapper.cpp
- this hugely reduces the memory used by rendering a timeline
with a lot of clips
- could be related to issue #239
=> free cache in FrameMapper::Close()

include/Frame.h, src/FFmpegReader.cpp, src/Frame.cpp, src/examples/Example.cpp, tests/FFmpegReader_Tests.cpp
Adding CheckPixel method and fixing a crash with certain hardware decode options enabled (which appears to be a recent regression). Also adding some new unit tests for this new method.
=> Adding new CheckPixel method to validate certain colors

CMakeLists.txt
This switches on the compiler option `-no-integrated-cpp` for GCC versions < 9, to work around a bug in the handling of `_Pragma()` directives in macros. This is necessary to make the "preferred" form of the PR #241 fixes (to silence deprecation warnings on some versions of FFmpeg) work with those GCC versions.
See [GCC bug 55578](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55578) and the discussion at #241 starting from [this comment](https://github.com/OpenShot/libopenshot/pull/241#issuecomment-503786187) for more details.
I tested this on my system, `-no-integrated-cpp` was inserted into the compiler command line with GCC 7.3.0, but was not with GCC 9.1.1. It should never be inserted with any compiler that doesn't have the short identifier "GNU", so it's safe around other build …
=> Add -no-integrated-cpp for G++ < 9

include/FFmpegUtilities.h, src/FFmpegWriter.cpp
The deprecated calls are and will be present in ffmpeg 3.x and later version use other calls. Therefore, the warning is useless and obscures only important warnings.
=> Silence deprecated warnings in ffmpeg 3.x

include/Frame.h, include/ImageReader.h, include/ImageWriter.h, include/MagickUtilities.h, include/TextReader.h, include/effects/Mask.h, src/Frame.cpp, src/ImageReader.cpp, src/ImageWriter.cpp, src/TextReader.cpp, src/effects/Mask.cpp
This PR is an alternative to #250 by @steils — honestly, it was never my intention to step on anyone's toes with this, and I wouldn't have continued with it if it wasn't already in progress by the time @steils submitted #250. But, it was, and I discovered a couple of things along the way that I thought made it worth continuing with. But I apologize to @steils for duplicating their work.
Just as in #250, this adds ImageMagick 7 compatibility to libopenshot without sacrificing ImageMagick 6 support. In the case of this PR, a new header `imclude/MagickUtilities.h` is created to hold the compatibility `#define`s.
Out of an overabundance of caution, I also wrapped the three headers and the three source files that are ImageMagick-only in `#ifdef USE_IMAGEMAGICK` statements. Even though the …
=> Add backwards-compatible Imagemagick 7 support

include/effects/Crop.h
Doxygen caught this one: the default constructor for the `Crop()` effect doesn't take an argument `color`, though it was documented to.
With the changes in #245, this will eliminate all of the Doxygen warnings when building the docs. Submitting this as a separate PR, though, because it's not really about Doxygen.
=> Crop.h: Remove nonexistent color argument

.gitlab-ci.yml
Our Linux builder now automatically builds the Doxygen HTML files, and auto-updates https://www.openshot.org/files/libopenshot/. This only happens for the "develop" branch, and only on our Linux builder.
This is related to a conversation from https://github.com/OpenShot/libopenshot/pull/245.
=> Auto update documentation (Doxygen)

include/OpenMPUtilities.h
When I build libopenshot and then `sudo make install` it, when I build my own software that uses the library I get an error:
```
/usr/local/include/libopenshot/effects/../OpenMPUtilities.h:35:10: fatal error: ../include/Settings.h: No such file or directory
```
It works with the new path in the PR.
=> Fix path to Settings.h

.travis.yml
Taking my own suggestion, this adds a `make install` step to all three (overkill, maybe?) Travis builds, using `DESTDIR=dist/` to keep the files local to the build dir. Meant to bring the CMake-managed install logic under CI verification.
=> Travis CI: Also run `make install`

src/FFmpegWriter.cpp
Add 2 new multiplexing presets for mp4, mov files:
* mp4_faststart
* mp4_fragmented
The Preset usage from openshot-qt export.py as follows (example):
w.SetOption(openshot.VIDEO_STREAM, "muxing_preset", "mp4_faststart")
YouTube suggest to use streamable file formats to process the uploading
videos faster (by starting its processing when upload not yet complete)
MP4, MOV files export requires additional dictionary keys to be set in
this case.
MP4/MOV is popular, so instead of using external utils, add support for
streamable export directly to OpenShot.
Cons (-):
- The fragmented output requires modern player to playback, otherwise
only first 4-8sec of footage will playback.
- Placing 'moov' box to the begging of the file doing more write operations
to the disk (box moved when file …
=> Add 2 new multiplexing presets for mp4, mov files

include/TextReader.h, src/TextReader.cpp
I'm keen to make some enhancements to the TextReader including text stroke. First I have added the ability to add a colored box around text. See the example image of how this looks:
I didn't want to add any more params to the constructor as it already has 10 params so I added a setter method.
Looking for feedback if I am taking the right approach before doing the stroke and to see whether these enhancements are desired by maintainers/users.
=> Add a text background colored box option to the text reader

include/CacheBase.h, include/ClipBase.h, include/ReaderBase.h, src/CacheBase.cpp, src/ClipBase.cpp, src/ReaderBase.cpp
Removing duplicate destructor definitions and implementations, so virtual destructors will not break on older toolchains. This PR is in response to https://github.com/OpenShot/libopenshot/pull/224.
=> Removing duplicate destructor definitions and implementations

src/bindings/python/CMakeLists.txt
OK, this adds in this fix with the #222 changes, which should protect against #227 
Python: Assume /usr/local prefix on Debian
If we're using the fallback path detection method on Debian, we
shouldn't compute the install path relative to `${CMAKE_INSTALL_PREFIX}`
since it _isn't_. So, we assume it's relative to `/usr/local` instead.
=> Don't break Python install path detection on Debian

src/bindings/python/CMakeLists.txt
Reverts OpenShot/libopenshot#229
All builders failed after merging https://github.com/OpenShot/libopenshot/pull/229. Attached are the errors on Mac and Windows (Linux worked fine, after adjusting 1 path on our gitlab-ci file).
[mac-builder-gitlab-output.txt](https://github.com/OpenShot/libopenshot/files/3316133/mac-builder-gitlab-output.txt)
[win-builder-gitlab-output.txt](https://github.com/OpenShot/libopenshot/files/3316134/win-builder-gitlab-output.txt)
=> Revert "Don't break Python install path detection on Debian"

src/QtImageReader.cpp
When using Resvg to render SVG files to pixels, we were accidentally rendering transparency into our original aspect ratio, and thus, common/SVG-based transitions appeared to be letter boxed. This is essentially a regression caused by our implementation of Resvg.
There are times during preview (at smaller resolutions) when transitions appear to be 1 pixel offset, caused by some aliasing. I'm not sure if this is specifically an resvg problem, or something larger related to source aspect ratios / Qt scaling / etc... Some discussion has taken place on this issue here: https://github.com/RazrFalcon/resvg/issues/153.
=> Fix resvg rendering issues for common transitions

include/effects/Brightness.h
The range was listed as 0 – 100, but implemented as -1 – +1. Edited documentation to reflect reality.
Reported by @jeffski like a year and a half ago.
Fixes #71
=> Correct parameter documentation for brightness

.gitlab-ci.yml
Moving 64-bit and 32-bit Windows builders to AWS, and updating all dependencies and build tools. MinGW Makefiles is no longer working, and it appears things have changed to MSYS Makefiles now. FYI: This will speed up our Windows builds quite a bit! (libopenshot)
=> Updating MSYS2, New Cmake builder syntax

include/Qt/PlayerDemo.h
keyPressEvent() overrides that of QWidget(), and ought be declared `override`.
=> PlayerDemo: declare keyPressEvent() override

.gitlab-ci.yml
This is related to our updated Windows builder I'm working on. Trying to get all the GitLab CI working again, with a few new file-paths.
=> Fixing python3.6 to 3.7 Windows reference

src/ZmqLogger.cpp
Adding logging support for resvg (which will output on stderr). I am currently troubleshooting an issue with resvg and Windows 10 + missing fonts. The resvg logging needs to be enabled to better troubleshoot issues with it.
=> Adding logging support for resvg

include/FFmpegUtilities.h
We've discussed how it would be good to enable `-Wall` when building libopenshot, to take advantage of gcc's sanity checks. (See, for example, [this comment thread](https://github.com/OpenShot/libopenshot/pull/224#discussion_r294090333) on #224.)
Unfortunately, current libopenshot produces a _lot_ of warnings with `-Wall`, some of them repeatedly because they're triggered in headers. This is one of those. As-is, `g++` will complain every time `FFmpegUtilities.h` is included that the `av_make_error_string()` function is unused, since there are no visible calls to it (they're all produced by a macro). Inlining the function causes it to be copied into each implementation where it's used, which gets it out of the header, eliminates those warnings, and arguably represents cleaner code since …
=> FFmpegUtilities: inline av_make_error_string

include/ZmqLogger.h, src/Clip.cpp, src/FFmpegReader.cpp, src/FFmpegWriter.cpp, src/FrameMapper.cpp, src/ImageWriter.cpp, src/Timeline.cpp, src/ZmqLogger.cpp
This is part of an effort I'm broadly calling "Don't make programmers write awkward code". It doesn't actually have anything to do with `-Wall`, it just addresses something that would keep catching my eye as I was visiting bits of code that _were_ flagged by `-Wall`.
If you poke around inside libopenshot's code for any length of time, you can't help but notice all those calls to `ZmqLogger::Instance()->AddDebugMethod()` that look like this:
```cpp
ZmqLogger::Instance()->AppendDebugMethod("Timeline::apply_effects (Does effect intersect)",
"effect->Position()", effect->Position(), "does_effect_intersect", does_effect_intersect,
"timeline_frame_number", timeline_frame_number, "layer", layer,"", -1, "", -1); 
```
The method takes 13 total arguments (an opening message, then six `(name, …
=> Default values for ZMQ logging calls

.gitignore
I tend to create multiple build paths at the root of the project, for testing various configurations. So I'll  have all of `build/`, `build-somebranch/`, `build-otherbranch/`, etc. sitting around. The current `.gitignore` will only ignore a directory named exactly `build`.
This PR updates the `.gitignore` for the repo to exclude `/build*`, meaning _anything_ with a name that starts with `build`, if it's located at the root of the repository tree.
=> Exclude all build* files/directories @ root level

CMakeLists.txt
This adds the same documentation install logic used in libopenshot-audio (since OpenShot/libopenshot-audio#56, plus the modifications in OpenShot/libopenshot-audio#59), so that running `make install` AFTER `make doc` will pick up the generated Doxygen output an install it into `${CMAKE_INSTALL_DOCDIR}/API`, which is `${CMAKE_INSTALL_PREFIX}/share/doc/libopenshot/API` on most systems.
=> Install documentation into DOCDIR/API, if built

include/Frame.h, src/bindings/python/CMakeLists.txt, src/bindings/python/openshot.i, src/bindings/ruby/CMakeLists.txt, src/bindings/ruby/openshot.i
This PR contains a bunch of changes to the SWIG generation, to make it possible to run with `CMAKE_CXX_FLAGS="-Wall -Wextra"` (and not be bombarded by errors from the generated code).
* Remove a SWIG pragma from `Frame.h` (gcc warns on it)
* Place the equivalent `%warnfilter` in the `openshot.i` files
* Populate `openshot.i` `PROPERTY` `GENERATED_COMPILE_OPTIONS` with flags to disable warning spew in generated SWIG code, if `-Wall` is used
(Also, remove 'using namespace std' from `Frame.h`, and add `std::` prefixes to necessary types.)
=> SWIG: Warnings cleanup

src/Clip.cpp
Currently "Enable Audio" and "Enable Video" default to `-1`, and can be modified to either `0` or `1`.
Those values are slightly cryptic for the average user, so this PR uses `add_property_choice_json()` to display  those values using the descriptive labels "Auto", "Off", and "On" (respectively).
=> Label "Enable Audio/Video" property values as Auto / Off / On

cmake/Modules/FindOpenShotAudio.cmake, src/CMakeLists.txt, tests/CMakeLists.txt
This PR is an overhaul of `FindOpenShotAudio.cmake` with things I needed for my local testing, but it should be more useful overall (fingers crossed that it works everywhere it's supposed to).
The major changes are:
1. **Version checking!** `find_package(OpenShotAudio 0.1.8 REQUIRED)` will now check that the version is at least `0.1.8`, and abort (because of the `REQUIRED`) if not.
The version is parsed from the `JuceHeader.h` file, and it would be _best_ with a merge of my PR OpenShot/libopenshot-audio#60, to generate that header during build. But, since we've had "0.1.8" hardcoded in there for a long time, it's fine even right now.
Other features:
- Supports `EXACT` (but only for M.N.B, e.g. `0.1.8-dev1` matches `0.1.8` EXACT)
- Outputs the following: (see below for examples)
- Version …
=> FindOpenShotAudio version reporting/validation, other fixes

src/bindings/python/CMakeLists.txt, src/bindings/ruby/CMakeLists.txt
@jonoomph discovered in #265 that SWIG 2.0 doesn't speak our dialect of C++11, which he fixed by upgrading to SWIG 3.0.8. So, bump the minimum SWIG version that CMake checks for.
=> Raise SWIG version requirement to 3.0

src/Frame.cpp
Flagged by `gcc -Wall`, a block of code was indented as if it was inside an `if()` statement, when it's not.
=> Frame.cpp: Fix misleading indentation

src/FFmpegReader.cpp
Move av_hwdevice_get_hwframe_constraints inside the part of the code only compiled when testing VAAPI constraint detection.
=> Move #endif

include/FFmpegUtilities.h, src/FFmpegWriter.cpp
This was causing unexpected problems with the `faststart` muxing option, because FFmpeg has to reopen the file to perform the second pass.
Fixes Openshot/openshot-qt#2921
=> Fix truncated output filenames in FFmpegWriter

src/AudioReaderSource.cpp, src/Clip.cpp, src/FFmpegWriter.cpp
I somehow missed a few calls, in #266.
=> Remove "dummy" args from ZmqLogger stragglers

include/ReaderBase.h, src/EffectBase.cpp, tests/ReaderBase_Tests.cpp
Various documentation comments gave instructions about how this or that class _must call_ `InitFileInfo()` — except, no such method exists.
(There is an `InitEffectInfo()`, also changed one comment to correctly reference it by the proper name.)
=> Remove mentions of nonexistent InitFileInfo()

CMakeLists.txt
The include paths listed in `OPENSHOT_INCLUDE_DIRS` by the root `CMakeLists.txt` all need to be absolute, so that `src/CMakeLists.txt` and the rest don't interpret them relative to _their_ current directory.
=> Fix include path list, for subdirectories

src/FFmpegReader.cpp
Attempt to fix the crash that was detected during investigation of the https://github.com/OpenShot/openshot-qt/issues/2828
This change doesn't fixes the desync issue mentioned in the report. It aims only at the crash resolve.
=> Fix crash during seeking at the start of the file

include/PlayerBase.h, include/QtPlayer.h, src/QtPlayer.cpp
`video_position` of the class `PlayerPrivate` declared as `int64_t` inside the _include/Qt/PlayerPrivate.h_
Note: The `ClipBase` class has its own `Position()` method that returns `float` (used in the Timeline operations, the latter has number of internal limits that is not affected by this PR).
=> Fix return type mismatch

src/examples/Example.py
Codacy pointed out that there's absolutely no reason to be
importing the sys module in this code.
=> Example.py: Remove useless `import sys`

src/CMakeLists.txt, tests/CMakeLists.txt
This change enhances the CMake configuration process with two changes:
1. Use `foreach()` loops, along with some list variables and `list(APPEND...)`, to cut down _greatly_ on repetitive code.
2. Use the CMake FeatureSummary module to display the build configuration.
For example, on my system, this results in:
```
Build configuration:
-- The following OPTIONAL packages have been found:
* ImageMagick
* PkgConfig
* OpenMP
* PythonLibs (required version >= 3)
* PythonInterp (required version >= 3)
* Ruby
-- The following REQUIRED packages have been found:
* FFmpeg
* OpenShotAudio (required version >= 0.1.8)
* Qt5Widgets
* Qt5Core
* Qt5Gui
* Qt5Network (required version >= 5.12.4)
* Qt5Multimedia
* Qt5MultimediaWidgets
* ZMQ
* SWIG (required version >= 3.0)
-- The following OPTIONAL packages …
```
=> CMake with loops! (And FeatureSummary)

.travis.yml
This PR modernizes our Travis build configs (no more manual `sudo`, packages managed using Travis' supported `apt` addon, etc.), as well as makes some updates:
* The FFmpeg 3 and 4 builds are upgraded to their Ubuntu 18.04 (Bionic) image. FFmpeg 2 remains on the 16.04 (Xenial) image
* The Bionic builds are also upgraded from Qt 5.10 to 5.12.3
* The FFmpeg 3 PPA is dropped, because Bionic includes FFmpeg 3 by default
=> Travis updates (Bionic, Qt 5.12, config)

include/CacheBase.h, include/ChunkReader.h, include/ReaderBase.h, src/CacheBase.cpp, src/ChunkReader.cpp, src/ReaderBase.cpp
The code to convert JSON values from string to numeric types was using the old C `atoll()` function from `stdlib.h` for type-conversion. But C++11 has `std::stoll()` to convert directly from `std::string`, instead of going through C byte strings.
This PR switches from `#include <stdlib.h>` to `#include <cstdlib>`, and rewrites the conversions to use `std::stoll()`.
=> Use std::stoll to convert JSON values

src/FFmpegReader.cpp
Move interlace detection to `UpdateVideoInfo()` so it'll be done before we read any frames, and use the `field_order` member of the codec attributes (an `AVFieldOrder` enum) as the data source.
In my limited testing, this seems to fix interlace detection in at least simple cases. I have an interlaced MPG file (a VHS capture), which FFmpegReader now properly reports as interlaced immediately after `Open()`. 
With the _old_ code, interlacing **was** being detected, but only _after_ reading the file (because `GetFrame()` was examining the input frame on read to determine scan parameters). This would explain the issues with `File Properties` in OpenShot not displaying correct data for interlaced files.
I do have a _different_ interlaced file which fails to detect as interlaced, even though …
=> FFmpegReader: Detect interlaced video on file open

include/OpenShotVersion.h.in, src/CMakeLists.txt, src/OpenShotVersion.cpp, src/bindings/python/openshot.i
With warnings enabled, `g++` was complaining about `GetVersion()` being unused every time the `OpenShotVersion.h` header file was included. So I separated out the implementation into `src/OpenShotVersion.cpp`, which silenced the warnings.
Then I added some conveniences, and some Pythonic flourishes:
1. I moved the initialization of the struct members to the struct itself, instead of in `GetVersion()`, and I made them `const`
1. I changed the const member names to uppercase first letter, since apparently Ruby has some rule about constants starting with a capital letter, and it complained otherwise (and renamed them anyway!)
1. I added a static `openshot::Version`, of type `openshot::OpenShotVersion`
1. I gave `openshot::OpenShotVersion` a string representation in the Python interface file …
=> Version information: Separate implementation, add pythonic touches

src/CMakeLists.txt, tests/CMakeLists.txt
OpenMP is now `REQUIRED` as the build will fail if it's not available. This PR updates the `find_package`, and creates the necessary targets for older CMake versions (3.9+ will do it automatically).
The targets are then made `PUBLIC` dependencies of the `openshot` target, which causes the OpenMP configs to automatically propagate. The redundant OpenMP detection is removed from `tests/CMakeLists.txt`.
The detection code comes verbatim from [this post](https://iscinumpy.gitlab.io/post/omp-on-high-sierra/), which also credits Modern CMake.
=> CMake: REQUIRE OpenMP, use (or create) targets for dependency propagation

src/FFmpegReader.cpp
`operator[]` for `std::map` [is documented](https://en.cppreference.com/w/cpp/container/map/operator_at) as auto-inserting and initializing members if they're not present, so this change just replaces as few lines of conditional "check-then-initialize-else-increment" logic with a simple `++checked_frames[frame]`, [a common pattern](https://en.cppreference.com/w/cpp/container/map/operator_at#Example).
=> FFmpegReader::CheckMissingFrame -- checked_frames std::map tweaks

include/QtImageReader.h, src/QtImageReader.cpp
This changes the type of the private `path` variable to QString internally (which we were converting it to for a bunch of operations anyway), and uses QString's more robust string-manipulation and
-comparison methods to ensure that only filenames that _end in_ an `.svg`/`.svgz` extension (case-insensitively) are recognized as SVG files.
Previously, a filename such as "Title.svg.png" would be interpreted as an SVG file.
The change in the `path` type is purely internal, all of the class's interfaces remain the same, and accept `std::string path`. We simply convert it to/from QString at opposite places in the code, now.
=> QtImageReader: Safer ReSVG file extension checks

src/bindings/python/CMakeLists.txt, src/bindings/ruby/CMakeLists.txt
The resetting of `CMAKE_SWIG_FLAGS` to the empty string, in the bindings' CMakeLists.txt files, was clearing away the definitions for things like `USE_IMAGEMAGICK` and `USE_BLACKMAGIC`. This caused the bindings to be built _without_ those classes even if they're available in the library.
(And it's been like that for _three and a half **years**_.)
=> Bindings: Apply #defines for optional libs

src/CMakeLists.txt, src/FFmpegReader.cpp, src/FFmpegWriter.cpp, src/examples/Example.cpp
(And mostly unrelated to hardware acceleration.)
- Clean up some misleading indentation in FFmpegWriter
- Replace this FFmpegReader message (printed on stdout):
```
Decodiing Device Nr: 2
```
With this:
```
Hardware decoding device number: 2
```
- Eliminate the hardcoded `/home/jonathan/` source-file path in `Example.cpp` by adding a definition of `TEST_MEDIA_PATH` to `src/CMakeListst.txt`, same as `tests/CMakeLists.txt`, and using that as the path to the input file.
=> Some minor fixes made while testing hwaccel

src/CMakeLists.txt, tests/CMakeLists.txt
We don't _just_ use the ZeroMQ library, we also use the optional (and external) cppzmq C++ bindings.
Previously we weren't detecting for those at all, mostly because Ubuntu just arbitrarily bundles them with its `libzmq3-dev` package. Most distros don't, and when packaged properly cppzmq includes appropriate CMake configuration to make itself discoverable.
This PR adds a check for those configs, and just adds its include dir to the build (as it's a header-only library).
=> CMakeLists: Also detect cppzmq headers

tests/FFmpegReader_Tests.cpp, tests/FFmpegWriter_Tests.cpp, tests/ImageWriter_Tests.cpp, tests/Timeline_Tests.cpp
Our internal `CheckPixel()` function takes a tolerance argument, and is always given a tolerance of 5 when it's used in the unit tests. But the unit tests require pixel values to be exactly `CHECK_EQUAL` to some specific level, which is not always the case on non-i686 / non-x86_64 platforms.
This change adds the same 5-value tolerance to the pixel-value unit tests, allowing the tests to more readily pass on ARM and other platforms.
Fixes #332 #51
=> tests: Add tolerance to pixel value checks

CMakeLists.txt, tests/CMakeLists.txt
CMake's decision to reserve certain target names (test, package) was amended in CMake 3.11, so that the names are only reserved when the feature in question (CTest, CPack) is actually used in the project.
So, with newer CMake versions, it's again possible to provide a `make test` command to build and run the unit tests. This PR enables that functionality if the CMake version is sufficiently new. The old `make os_test` target is preserved for backwards-compatibility, and should still be preferred for build/CI purposes.
This change also adds a message to the CMake generation output detailing what targets are available for unit tests, and updates the documentation target with a similar message (if Doxygen i available).
=> Re-enable 'make test' when possible (requires CMake 3.11+)

src/ImageReader.cpp, src/QtImageReader.cpp, src/TextReader.cpp
The 24 hours duration seems to be creating millions of additional frames (24 hours worth) in the FrameMapper for text readers and I presume image readers to as they are just single image frames. This is causing massive memory spikes in the text reader everytime a new TextReader is added.
Not sure why the duration is set to 24 hours, as far as I can tell everything works as expected with a duration of 1 and the memory issue is gone.
Fixes issue #327
=> Stop 24 hours worth for frames being loaded in to memory (#327)

CMakeLists.txt, tests/CMakeLists.txt
I found myself sympathetic to the argument (made in #17) that `DISABLE_TESTS` should completely prevent CMake from even entering the `tests/` dir. So, with this PR, that's what it does.
Fixes: #17
=> DISABLE_TESTS covers entire tests/ dir

CMakeLists.txt
This bumps the minimum CMake version just _slightly_ to `3.2` (from `3.1`), as 3.2 was when the propagation of target properties to linked targets was fully realized in the source. While our current `CMakeLists.txt` files _seem_ to work with CMake 3.1, at least on Linux, I'm concerned there may be subtle breakages down the line. CMake 3.2 should be far safer, and is still well within the realm of what we can reasonably expect to have on even the oldest still-supported systems.
Output of the `${CMAKE_VERSION}` variable is also added to the config stage:
<pre><code>
$ cmake32 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_VERBOSE_MAKEFILE=1 -DDISABLE_TESTS=1 ..
-----------------------------------------------------------------
Welcome to the OpenShot Build System!
CMake will now check …
=> Bump CMake min-version to 3.2, display during build

src/bindings/python/CMakeLists.txt
This is a hail-mary _attempt_ to fix Python install-path logic for non-Debian systems, without breaking things for the Debian folks. Because currently, the Debian special-casing is causing the **wrong** install path to be chosen on Fedora and other `lib64`-using systems, a regression from previous behavior (up to and including 2.4.4-release) where the proper `/usr/lib64/...` path was correctly chosen.
The path `${CMAKE_INSTALL_PREFIX}/lib/pythonM.N/site-packages` is not Debian-specific, and will exist on too many systems where it should _not_ be assumed to be the correct install path.
=> Python install path: remove site-packages detection

include/AudioBufferSource.h, include/AudioReaderSource.h, include/AudioResampler.h, include/CacheBase.h, include/Clip.h, include/Frame.h, include/ReaderBase.h, include/ZmqLogger.h, src/AudioBufferSource.cpp, src/AudioReaderSource.cpp, src/AudioResampler.cpp, src/CMakeLists.txt, src/Clip.cpp, src/Frame.cpp, tests/Cache_Tests.cpp, tests/Clip_Tests.cpp, tests/Color_Tests.cpp, tests/Coordinate_Tests.cpp, tests/FFmpegReader_Tests.cpp, tests/FFmpegWriter_Tests.cpp, tests/Fraction_Tests.cpp, tests/FrameMapper_Tests.cpp, tests/ImageWriter_Tests.cpp, tests/KeyFrame_Tests.cpp, tests/Point_Tests.cpp, tests/ReaderBase_Tests.cpp, tests/Settings_Tests.cpp, tests/Timeline_Tests.cpp
So, I spent part of the weekend running libopenshot through [include-what-you-use (IWYU)](https://github.com/include-what-you-use/include-what-you-use/), a `#include` scanner that attempts to help you... well, it [does exactly what it says on the tin](https://en.wikipedia.org/wiki/Does_exactly_what_it_says_on_the_tin). I may have some changes to submit along those lines down the road, but this PR isn't actually about that.
IWYU is based on, and runs best with, Clang, so in order to run the code through IWYU I first had to get it buildable under Clang. This PR is the work necessary to make that happen.
It was actually fairly easy; the main library source _initially_ didn't require any changes at all.
What _did_ ultimately force me to make changes, and where things snagged up a bit at …
=> Add fixes for Clang/IWYU building, correct juce:: namespacing

src/CMakeLists.txt
I messed up the `ENABLE_IWYU` handling in #352, so that it wouldn't be run if you _didn't_ set `IWYU_OPTS`. This fixes that.
It also adds a `CMAKE_VERSION` check to disable IWYU checking in CMake 3.2, since support for it wasn't introduced until CMake 3.3. Under CMake 3.2 it won't be run even if it's installed and present. (A note to that effect is placed in the `OPTION` doc string.)
=> CMake: Fix IWYU invocation with unset IWYU_OPTS

.gitlab-ci.yml
Fix for the official package builder, in the wake of merging #348.
=> Use bundled JsonCPP on linux builder

cmake/Modules/FindZeroMQ.cmake, src/CMakeLists.txt
Windows finds only the _static_ version of the library (`libzmq.dll.a`, but not `libzmq.dll`), which the `FindZeroMQ.cmake` from cppzmq places in a different target (`libzmq-static`).
It was also creating _both_ targets, with the `libzmq` `IMPORTED LOCATION` set to `libzmq-NOTFOUND`.
That's not particularly helpful, so it's been updated to only export `FOUND` targets, and `src/CMakeLists.txt` will link only the existing one — preferring `libzmq` (`SHARED`), falling back to `libzmq-static` if necessary.
=> Fix target creation/importing for ZeroMQ on Windows

.gitlab-ci.yml, cmake/Modules/FindZeroMQ.cmake, src/CMakeLists.txt
Not 100% sure _why_, honestly, but this version of the Find module works where the previous one didn't.
I believe it comes down to this note in the CMake docs for `add_library`:
<blockquote>An UNKNOWN library type is typically only used in the implementation of Find Modules. It allows the path to an imported library (often found using the find_library() command) to be used without having to know what type of library it is. <b>This is especially useful on Windows where a static library and a DLL’s import library both have the same file extension.</b></blockquote>
This also does away with the `ZMQ_DIR` envvar entirely — `ZeroMQ_DIR` can be set as a CMake variable (`cmake -DZeroMQ_DIR:PATH="C:\msys64\mingw64\"`, for example) to provide the location of ZeroMQ.
But that actually shouldn't be …
=> Fix Windows ZeroMQ for real

.travis.yml
Now that libopenshot is buildable with Clang, this adds it as another job in the Travis CI build matrix.
(It tests FFmpeg 3 simply because that was the shortest, simplest build configuration to duplicate. Be nice if our builds used an actual matrix-based configuration and clang could just be added as another dimension, but alas we're not there yet.)
=> Add Clang compilation to Travis build matrix

src/bindings/python/CMakeLists.txt
Detecting PythonLibs before PythonInterp can cause a non-default Python
library to be picked up, which then won't match the PythonInterp version
(which always matches the version of the `python3` command).
(e.g. on Fedora 30 with `python3-3.7.5` and `python3-libs-3.7.5` installed as the default `/usr/bin/python3`, plus `python38-3.8.0` installed as `/usr/bin/python38`...)
1. With `find_package(PythonLibs 3)` before `find_package(PythonInterp 3)`:
```
-- Found PythonLibs: /usr/lib64/libpython3.8.so (found suitable version "3.8.0", minimum required is "3") 
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.7.5", minimum required is "3") 
```
2. With `find_package(PythonInterp 3)` before `find_package(PythonLibs 3)`:
```
-- Found PythonInterp: /usr/bin/python3 (found …
```
=> Reverse order of Python detection

include/QtHtmlReader.h, include/QtTextReader.h
- Some parameters were changed from documented list
- Hash signs need to be escaped if they're not references (links)
=> Fix documentation for Qt(Text/Html)Reader

CMakeLists.txt, cmake/Modules/FindFFmpeg.cmake, src/CMakeLists.txt, src/bindings/ruby/CMakeLists.txt, tests/CMakeLists.txt
This is kind of a major one. Not only does it move to using the Qt targets for linking, but it:
* switches over to AUTOMOC instead of manually wrapping files (some of which never needed to be wrapped),
* removes the globbing for `src/effects/` and `src/Qt/` files. (All source files now have to be named explicitly in `src/CMakeLists.txt`, so if any are added the appropriate list needs to be updated.)
* Calls `include_directories()` once from the top level `CMakeLists.txt`, and then not again.
* Eliminates the `REQUIRED_LIBRARIES` variable from CMake, continuing the process begun in previous `IMPORTED`-target PRs where dependencies get linked separately using multiple `target_link_libraries()` calls.
* <strike>Switches to `$<$<BOOL:Foo_FOUND>:${Foo_LIBRARIES}>` generator expressions, for …
=> CMake: Use targets for QT, AUTOMOC sources, eliminate source globbing

src/FFmpegReader.cpp, src/FFmpegWriter.cpp
Fixing a small implementation detail related to using high quality scaling in FFMpegWriter, and switching from SWS_LANCZOS to SWS_BICUBIC, for better quality when upscaling images (with a small performance loss). But sharper exports are aim, and if it costs us 1 or 2% slower speed, it seems worth it to me.
Real-time previews still use a faster algorithm: SWS_FAST_BILINEAR.
Some comparisons of the FFmpeg scaling methods: 
http://www.programmersought.com/article/4493483389/
=> Change high quality scaling to use SWS_BICUBIC

src/Frame.cpp
As mentioned in issue #202 `QImage::bits()` and `QImage::scanLine()` make a deep copy of the source image.  This is completely unnecessary when read-only access to the pixel data is required.  Changing to `QImage::constBits()` and `QImage::constScanLine()` solves this.  Both functions were introduced in Qt 4.7.
Tested using some test project in OpenShot, not sure if I covered all cases, though!
https://doc.qt.io/qt-5/qimage.html#constBits
=> Frame.cpp: Avoid unnecessary copy of image data

CMakeLists.txt, Doxyfile.in
- Define `USE_IMAGEMAGICK` and `USE_BLACKMAGIC` unconditionally when building docs, so that the classes will be documented.
- Improve handling of `std::`-prefixed types in doxygen output.
=> Minor adjustments to Doxygen API docs

src/Clip.cpp, src/Timeline.cpp
When warnings are enabled, the compiler will flag any lines of the form:
```c++
if (result = get_result_for(thing))
```
due to the possibility that it's either _meant_ to be an equality test, or will be _interpreted_ as an equality test by someone reading the code in the future.
The warnings can be silenced by adding a second set of parens, i.e.
```c++
if ((result = get_result_for(thing)))
```
or, as this PR makes it (for readability, at the end of the line):
```c++
if ( (result = get_result_for(thing)) )
```
Double parens are added to the three remaining places in the code which trigger that warning.
=> Wrap parentheses around assignment in conditional

include/KeyFrame.h, src/Clip.cpp, src/KeyFrame.cpp, src/Timeline.cpp, tests/Color_Tests.cpp, tests/KeyFrame_Tests.cpp
This is a new implementation of the Keyframe class.
**Differences**
The main difference is that the old implementation was "fully cached" - by which I mean that it computed all interpolated values for all X coordinates on first request, and had to re-compute all values when anything changed.
The new implementation is completely "on demand", it does not cache any previously computed value(s) but instead computes just the one requested value for each `GetValue()`, `GetInt()` or `GetLong()` call.  This means modifications to the points do not invalidate any cache (as there is none) and are thus fast.
Regarding points: The previously public data member `Points` is now private and needs to be modified via the provided `AddPoint` and `RemovePoint` functions.  Some code outside of the Keyframe …
=> New Keyframe implementation

src/bindings/python/openshot.i
The new Pythonic `openshot.Version` has a string representation, so these will all work:
```python
>>> import openshot
>>> print(openshot.Version)
0.2.3-dev1
>>> str(openshot.Version)
'0.2.3-dev1'
>>> print("Version: {}".format(openshot.Version))
Version: 0.2.3-dev1
>>> str(openshot.Version) > '0.2.3'
True
>>> str(openshot.Version) > '0.2.4'
False
```
But used interactively, this happens:
```python
>>> openshot.Version
<openshot.OpenShotVersion; proxy of <Swig Object of type
'openshot::OpenShotVersion *' at 0x7f42f4a8bd80> >
```
So, this PR adds a `__repr__` method that returns a representation of the version object, in place of the autogenerated SWIG text:
```python
>>> import openshot
>>> openshot.Version
OpenShotVersion('0.2.3-dev1')
```
Note that this is only the _representation_ — …
=> Add repr to openshot.Version

CMakeLists.txt, src/CMakeLists.txt
PR #367 by @musteresel adds optional coverage reporting to the CMake build, which is controlled from the root `CMakeLists.txt` and `tests/CMakeLists.txt`.
Until now our FeatureSummary output has been done in the `src/CMakeLists.txt`, but it makes sense to list coverage reporting as a build feature. So, the FeatureSummary generation is moved to the bottom of the root `CMakeList.txt` where it can collect feature information from all build components.
=> Move feature summary to root CMakeLists

.travis.yml
As I noted in https://github.com/OpenShot/libopenshot/pull/386#issuecomment-564573049 :
The failed Travis check is due to our FFmpeg 4 build failing in the setup phase, as it's not able to install the ffmpeg 4 libs via apt. It seems the maintainer of the PPA for ffmpeg 4 on Bionic has chosen to [take his toys and go home](https://launchpad.net/~jonathonf/+archive/ubuntu/ffmpeg-4):
<blockquote>
This PPA has been removed from public access as part of a protest against the abuse of open-source projects by large companies. For more detail visit the main page here: <a href="https://launchpad.net/~jonathonf">https://launchpad.net/~jonathonf</a>
If you are a company and you would like this PPA to continue then let me know your preferred route for contributions and I will arrange something.
If we …
=> Travis: allow FFmpeg4 build failures

src/FFmpegWriter.cpp
In #384 some issues were identified compiling libopenshot with `libav`, instead of `ffmpeg`. These adjustments make our source compatible with both.
- libav defines `AV_CODEC_ID_HEVC` but not `AV_CODEC_ID_H265`, so it makes sense to only use `_HEVC` in the source.
- `AVCodecContext->framerate` was actually added in FFmpeg 2.2, which corresponds to libavcodec 56.26. Our version check was using `LIBAVFORMAT_VERSION` instead of `LIBAVCODEC_VERSION`, and wasn't precise enough.
Fixes #384
=> FFmpegWriter: Some fixes for building with libav

CMakeLists.txt, cmake/Modules/CodeCoverage.cmake, tests/CMakeLists.txt
Uses CodeCoverage.cmake from [1] to build libopenshot with gcov
support.  Option ENABLE_COVERAGE enables this and sets a target
test_coverage which builds and runs openshot-tests and collects
coverage information into a html report.
I'm currently using this to make sure everything that I'm going to modify is covered by at least some test.  If this is useful it might even be interesting to add `make test_coverage` to a travis build to gather the resulting report as artifact.
Coverage reports should be made with `CMAKE_BUILD_TYPE` set to Debug, otherwise the report might be a bit strange.  The libopenshot generate with `ENABLE_COVERAGE=ON` should of course *NOT* be used by external projects ...
[1]: https://github.com/bilke/cmake-modules/blob/master/CodeCoverage.cmake
=> Enable coverage reporting for openshot-test

src/FFmpegWriter.cpp
- most of the time the fixed number being sent in was large enough,
but not always
- also added logging if avcodec_fill_audio_frame fails
=> fix incorrect buffer size being passed to avcodec_fill_audio_frame

src/FFmpegWriter.cpp
- sometimes the output from the SWR_CONVERT is not the exact amount we asked for
- without this fix, the old code would sometimes read past the end of a buffer
- valgrind complained about the old code
- read https://stackoverflow.com/questions/39587839/libswresample-swr-convert-not-producing-enough-samples
- @ferdnyc this is my holiday present to you :)
=> correctly calculate remaining_frame_samples

.travis.yml
This builds on @musteresel 's work to get coverage-reporting working (#367), by adding a new Travis build instance that generates the coverage report. It will then upload the report to [the libopenshot project at Codacy](https://app.codacy.com/manual/OpenShot/libopenshot/dashboard) for analysis.
The `allow_fail` tag is also removed from our FFmpeg4 build, as it seems the PPA walkout has ended.
=> Travis: Add coverage + uploading to Codacy, and un-failjail FFmpeg4

src/AudioBufferSource.cpp, src/AudioReaderSource.cpp, src/CacheBase.cpp, src/CacheDisk.cpp, src/CacheMemory.cpp, src/Clip.cpp, src/FFmpegWriter.cpp, src/Frame.cpp, src/FrameMapper.cpp, src/KeyFrame.cpp, src/ReaderBase.cpp, src/Timeline.cpp, src/effects/Wave.cpp, tests/Cache_Tests.cpp, tests/Clip_Tests.cpp
A frequent cause of complaining from `gcc -Wall` is comparison between types with different signedness. For instance, both of these will produce a warning:
```c++
std::vector<openshot::Point> points = {};
for (int i = 0; i < points.size(); i++) {
// stuff
}
Json::Value root = {};
for (int j = 0; j < root["clips"].size(); j++) {
// json stuff
}
```
Fortunately, both are easily solved:
```c++
std::vector<openshot::Point> points = {};
for (std::vector<openshot::Point>::size_type i = 0; i < points.size(); i++) {
// stuff
}
Json::Value root = {};
for (Json::Value::ArrayIndex j = 0; j < root["clips"].size(); j++) {
// json stuff
}
```
This PR applies similar solutions to all comparisons which cause a warning to be emitted.
=> Don't compare differently-signed types

src/FFmpegReader.cpp, src/FFmpegWriter.cpp, src/Timeline.cpp
When compiling with `-Wall`, GCC will issue a warning whenever a `switch()` on an enum type doesn't account for all of the possible enum values, either through explicit `case` statements or by including a `default` case.
This PR silences all of those warnings, by ensuring that all enum values are covered in `switch()` statements.
=> Ensure switch statements on enums cover all values

include/EffectBase.h, src/EffectBase.cpp
Not a single effect uses `info.short_name`, it is _always_ set to the empty string. And not a single consumer of the class or its derived classes (in either libopenshot or OpenShot) ever looks at it.
=> EffectBase: Remove unused short_name

src/effects/ColorShift.cpp
The `info.class_name` was set to `"Color Shift"`, an unlikely-seeming class name considering it contains a space character.
=> ColorShift effect: Correct class_name

include/AudioBufferSource.h, include/AudioReaderSource.h, include/AudioResampler.h, include/Clip.h, include/ClipBase.h, include/Frame.h
As I mentioned in #352, a few of libopenshot's headers contain `#define`s that were intended to work around issues with the JUCE library headers. But those things are best handled in other ways.
This PR removes forced defines for:
`__JUCE_UNITTEST_JUCEHEADER__`
`_NDEBUG`
=> Remove JUCE defines

src/Frame.cpp
During a DeepCopy of a Frame instance, we don't copy our max_audio_samples variable... which is set when adding audio to the audio buffer. This is mostly an optimization, but with the side effect of needing to be copied to new frame object copies.
This should resolves issues with https://github.com/OpenShot/libopenshot/pull/397.
=> Copy max_audio_samples with Frame::DeepCopy

src/Frame.cpp, tests/CMakeLists.txt, tests/Frame_Tests.cpp
Fix a typo I spotted in https://github.com/OpenShot/libopenshot/pull/395#issuecomment-568930523.
=> Frame: Copy has_audio_data correctly in DeepCopy

src/Timeline.cpp
Attempt to fix the: https://github.com/OpenShot/openshot-qt/issues/2882
**Edit:** as soon as PR was updated the info below is not actual anymore.
It is hard to read it as git differences/changed but I have added only:
```	// Clip that forced no video should has zero size output
if (source_clip->has_video.GetInt(clip_frame_number) == 0) {
source_size = QSize(0, 0);
// Debug output
ZmqLogger::Instance()->AppendDebugMethod("Timeline::add_layer (has_video = 0)", "source_frame->number", source_frame->number, "source_width", source_size.width(), "source_height", source_size.height());
}
else
```
before the `switch()`. I tried other formatting as well, but git changes still shown apart...
=> Skip painter transform for the Clip when video disabled

.travis.yml
Even though we bundle a copy of jsoncpp, it makes more sense to test our builds against the distros' system packages. Our copy is static, whereas the system packages could be updated. If that happens, testing in CI will hopefully help us catch any incompatibilities that get introduced (from either end).
=> Travis: Add libjsoncpp-dev to apt package list

cmake/Modules/FindRESVG.cmake, src/CMakeLists.txt, src/QtImageReader.cpp, tests/CMakeLists.txt
resvg should be rendering to `QImage::Format_ARGB32_Premultiplied`, according to @RazrFalcon.
Also, tightened up the code a bit. Works fine on my system, but the AppImage will be the ultimate test.
=> Fix Resvg image format

cmake/Modules/FindRESVG.cmake
I left a bunch of debug `message()`s in the FindRESVG.cmake module.
=> FindRESVG: Remove debugging messages

.travis.yml, codecov.yml
[Codacy](https://codacy.com) shows some promise, and I'd still like to use it eventually because it does a whole lot of complex tracking for repo changes, and as noisy and alarmist as it can be, for the most part I like its static analysis reporting.
But, so far setting coverage reporting up hasn't worked, the reports just don't seem to be getting there. meanwhile, setting the repo up at [codecov.io](https://codecov.io/) was a total breeze, it Just Worked™ right away. So, let's funnel our reporting there for now. It's something, at least.
=> Use Codecov.io for coverage reporting

src/Qt/VideoCacheThread.cpp
At least on my 4-core, far from high-performance system, the effect this has on playback stuttering and smoothness is _immense_.
With a 32-frame cache, even with debug logging enabled the preview is _largely_ smooth, at least when playing a Timeline with a single, unedited clip on it. With only 8 frames of buffer to work with, playback is jerky and stuttering even in that simple, best-case scenario.
=> Raise preview cache to CPUs*8 frames, max 64

src/KeyFrame.cpp
Signed-off-by: Christoph Willing <chris.willing@linux.com>
This resolves compilatin problem:
~~~
error: call of overloaded 'abs(double)' is ambiguous`
~~~
by  using fabs(double) from cmath rather than trying abs(int) from stdlib.h or  std::abs(long long int) from cstdlib
=> Resolve ambiguous abs() call

.travis.yml, doc/HW-ACCEL.md, include/FFmpegReader.h, include/FFmpegUtilities.h, src/FFmpegReader.cpp, src/FFmpegWriter.cpp
As noted in #436, our hw-accel code was never really compatible with FFmpeg 3.2.
This PR also adds an FFmpeg 3.2 build to our Travis matrix, ensuring that builds against that version are tested in the future.
Fixes #436 
Fixes #433
=> Limit HW accel support to FFmpeg 3.4+

src/CMakeLists.txt
- Only set `AUTOMOC` property on library target
- Only use the Qt headers in `target_sources()`
- Make Qt headers `PRIVATE` sources, to avoid migration to other targets
=> CMake: Limit scope of AUTOMOC

src/effects/ColorShift.cpp
For no discernible reason, the Color Shift effect initializes itself with the following properties:
|Property|Value|
|-----------|-------|
|Alpha X Shift|0.00|
|Alpha Y Shift|0.00|
|<b>Red X Shift</b>|<b>-0.05</b>|
|Red Y Shift|0.00|
|<b>Green X Shift</b>|<b>0.05</b>|
|Green Y Shift|0.00|
|Blue X Shift|0.00|
|Blue Y Shift|0.00|
The random "defaults" are arbitrary and unnecessary, and just complicate management of the effect parameters. This PR loses them, and inits all of the shifts to `0.00`.
=> ColorShift effect: Don't init with random values

src/effects/Saturation.cpp
Once again, Saturation was fairly efficient already, but adding `#pragma omp parallel for` and eliminating some intermediate variable storage allows it to run roughly twice as fast on my system, and I would expect even better results from a more powerful CPU.
=> Saturation: streamline and parallelize

src/effects/Pixelate.cpp
No real improvements this time, to be honest, since there's no real room for parallelization or optimization in the Pixelate code — it's pretty tight already.
However, I did rewrite it to make use of Qt's `QRect` and `QMargins`, in defining the area being pixelated. Which I think makes for marginally cleaner code (and certainly quite a bit shorter!), despite the lack of any significant performance impact.
=> Rewrite of Pixelate effect

src/effects/Wave.cpp
You know the drill by now. Main `for()` loop decorated with `#pragma omp parallel for`, and streamlined for cleaner parallelization.
In this one I also eliminated an unnecessary copy of the frame image data, taking advantage of QImage's implicit data sharing and automatic copying functionality to use the frame image's `constBits()` as the _source_ pixel data, and (an implicitly-copied) `bits()` as the destination.
11-second Big Buck Bunny clip export time on my 4-core system: `28s`, down from `1m24s` (nearly 3x as fast).
=> Streamline and parallelize Wave effect

include/effects/Blur.h, src/effects/Blur.cpp
This PR optimizes the Blur effect (by far our slowest effect), streamlining the code and (most importantly) adding OMP `#pragma`s to multi-thread the execution where the operations can be cleanly parallelized.
<strike>It still won't win any speed trophies (in fact, it's still slow as _fuck_), but testing on my 4-core Intel i5 system, during an export of an 11-second Big Buck Bunny clip with a default-settings Blur applied:
* CPU usage went up from 25% to 85%-95%
* Export rate estimation increased from 0.57 FPS to > 1.2 FPS, making the new code more than twice as fast
* I don't know what the full export time would have been for the old code because I gave up and canceled after 2 minutes when it was only at 20%. But with the new code, the full export completed in `4m37s` — so, again, more …
=> Optimized, parallelized Blur effect

src/Frame.cpp
Reading through the `openshot::Frame` code trying to debug the image-format switch, I came across the mess that was the current version of this method:
```c++
openshot::Frame::AddImage(QImage new_image, bool only_odd_lines) {
}
```
It's a good thing it's only called from one spot in the FrameMapper code, because holy _crap_ is it broken! Over the years, changes piled up that just kept moving it further away from what it was supposed to be doing, and because there are no unit tests for interlaced video, they were never noticed. I'm not surprised our interlaced support is broken! I don't know that this will fix it, but it should at least _un-break_ this particular method.
I had to go way, way back in the git history to find the ImageMagick version that it evolved from. Here's the original …
=> Frame: Fix interlaced AddImage

include/FFmpegReader.h, include/FFmpegWriter.h, src/FFmpegWriter.cpp, tests/FFmpegWriter_Tests.cpp
Add overloaded forms of `SetVideoOptions()` and `SetAudioOptions()` that apply some sensible defaults to rarely-changed parameters.
=> FFmpegWriter: Overload Set___Options() methods

CMakeLists.txt, cmake/Modules/FindUnitTest++.cmake, tests/CMakeLists.txt
- A new CMake option, ENABLE_TESTS, is created and defaults ON; pass `-DENABLE_TESTS=0` to disable. (Legacy `-DDISABLE_TESTS=1` will also override)
- Target info for docs and tests is shown in the FeatureSummary
- UnitTest++ is now `RECOMMENDED`, not `REQUIRED`, since libopenshot can be built without running unit tests
I also briefly broke `FindUnitTest++.cmake`, at one point completely changed the name to `FindUnitTestCpp.cmake`, and then ended up restoring the original name.
(There's a bug in CMake that prevents certain features of `FindPackageHandleStandardArgs()` from being used with module names that contain regular expression special characters (like `+`) — I actually submitted a change to CMake that _fixes_ that issue, which [was …
=> CMake: Add Features for docs, unit tests

src/EffectInfo.cpp
This fix is already on the release branch, merging here for completeness' sake.
=> ColorShift: Use one-word name in EffectInfo

.github/stale.yml
Experimental support for `stale` plugin, to help with issue management on GitHub. https://github.com/marketplace/stale
Related PR for libopenshot-audio: https://github.com/OpenShot/libopenshot-audio/pull/93
=> Adding stale bot for github issue management (libopenshot)

tests/ReaderBase_Tests.cpp
This PR completes coverage for the `ReaderBase_Tests.cpp` file _itself_, by adding code to exercise the derived class that's defined in the test source. (It does nothing to affect the coverage of any libopenshot source code, merely the coverage of the source code for the unit test itself.)
=> ReaderBase_Tests: 100% internal coverage

include/Settings.h, include/Timeline.h, src/Clip.cpp, src/Timeline.cpp
Adding ability for a Clip to auto-detect and instantiate a Timeline Reader from the *.osp file type. Added new Timeline constructor, to auto load UTF-8 JSON file, and regex convert all paths to absolute. Fixed a dead lock issue when a Timeline loads another Timeline.
This is the first big step towards allowing multiple *.osp files to exist inside an OpenShot Project. This opens up an infinite number of cool possibilities, such as splitting projects into scenes, and then combining scenes at the end. Or importing templates (i.e. *.osp projects) with the complexity hidden from the user (since it looks like a normal clip). I have big plans for this soon!!!
However, performance seems suspect currently, and we'll need to dig deeper, and determine how to most efficiently set thread limits and …
=> Adding ability for a Clip to auto-detect and instantiate a Timeline Reader

.travis.yml
_(...Ignore the branch name, which I subsequently realized was backwards.)_
This PR drops the separate FFmpeg 3.4 GCC job from our Travis configs. The Coverage job is running with the exact same config, so it serves as a test of that configuration. There's no reason to build it twice.
(I've been noticing that having a sixth job in Travis seems to be causing that last job to lag behind the rest a bit. Feels like 5 is our limit for concurrent jobs, so the sixth one ends up having to wait before it can start. Which is adding a couple of minutes or more to our total CI runtime.)
=> Travis: Drop extra FFmpeg 3.4 GCC job

codecov.yml, tests/Clip_Tests.cpp
UnitTest++ has its own exception handling (you can even `CHECK_THROW()` to test that a call throws an exception as expected), so the try/catch blocks in the Clip unit tests serve no purpose except to add unreachable code.
This PR replaces them with `REQUIRE CHECK_EQUAL(true, success);` checks on the result var from the previous call (the one that, when it was found false, the test used to `throw()`).
=> Clip_Tests: Remove try/catch blocks

.gitlab-ci.yml, .travis.yml, src/bindings/python/CMakeLists.txt, src/bindings/ruby/CMakeLists.txt
This is an attempt to fix the install paths for the bindings files, in particular the Ruby bindings which have been installing to an absolute path (which causes problems when building as non-root). In addition, the Gitlab builder scripts were _moving_ Python artifacts from their installed locations to `${CMAKE_INSTALL_PREFIX}/python`, which is just silly.
Now, `PYTHON_MODULE_PATH` or `RUBY_MODULE_PATH` can be defined on the CMake command line, and they'll override the detection process. (They're interpreted relative to the install prefix, so just `-DPYTHON_MODULE_PATH=python` recreates the previous scripted output.
In addition, the module paths on Windows and MacOS default to simply "python" or "ruby" instead of bothering with detection, since we don't install on the system there anyway.
=> bindings: Relative paths, overridable

src/QtImageReader.cpp, src/ZmqLogger.cpp
This PR resolves both of the deprecations showing up in the codebase when building with current dependency versions.
* Qt's <strike>`QImage::sizeInBytes()`</strike>, used once in QtImageReader, <strike>is deprecated</strike> starting with Qt 5.10. (Correction: `QImage::byteCount()` is deprecated, `QImage::sizeInBytes()` is its replacement.)
* ZeroMQ deprecated the `send()` form we've been using starting with version 4.3.1.
The replacement ZMQ API includes a second `flags` argument. We take advantage of the new field to specify `zmq::send_flags::dontwait`, flagging the message for immediate delivery. (It's possible we could use `dontwait` in older ZMQ versions, so perhaps the version check could be broadened. It's also possible that `dontwait` has a negative performance impact, in which …
=> Add version gating for Zmq and Qt deprecations

src/ZmqLogger.cpp
zmq.h
```
#define ZMQ_VERSION_MAJOR 4
#define ZMQ_VERSION_MINOR 3
#define ZMQ_VERSION_PATCH 1
#define ZMQ_MAKE_VERSION(major, minor, patch)                                  \
((major) *10000 + (minor) *100 + (patch))
#define ZMQ_VERSION                                                            \
ZMQ_MAKE_VERSION (ZMQ_VERSION_MAJOR, ZMQ_VERSION_MINOR, ZMQ_VERSION_PATCH)
```
error without fix:
```
$ make
[  1%] Automatic MOC for target openshot
[  1%] Built target openshot_autogen
Scanning dependencies of target openshot
[  2%] Building CXX object src/CMakeFiles/openshot.dir/ZmqLogger.cpp.o
/home/chiller/Desktop/git-extern/libopenshot/src/ZmqLogger.cpp: In member function ‘void openshot::ZmqLogger::Log(std::__cxx11::string)’:
/home/chiller/Desktop/git-extern/libopenshot/src/ZmqLogger.cpp:12 …
```
=> Fix zmq version check

src/bindings/ruby/CMakeLists.txt
Ruby 2.7.0 contains some SWIG incompatibilities that weren't addressed until the (unreleased) SWIG 4.0.3, so if we detect the new Ruby version, emit a warning when generating the build. (The warning can be silenced by the user, as indicated.)
```
-- Found Ruby: /usr/bin/ruby (found version "2.6.5") 
CMake Warning at src/bindings/ruby/CMakeLists.txt:51 (message):
Ruby 2.7.0+ detected, building the libopenshot Ruby API bindings requires a
pre-release version of SWIG 4.0.3 with this commit:
https://github.com/swig/swig/commit/5542cc228ad10bdc5c91107afb77c808c43bf2a4
-- 
To disable this warning, add -DSILENCE_RUBY_VERSION_WARNING:BOOL=1 to the cmake
command line, or enable the option in the CMake GUI.
```
(I had temporarily set the version comparison down to 2.6.0 to force the warning for …
=> Add SWIG/Ruby compatibility check & warning

cmake/Modules/FindZeroMQ.cmake, src/ZmqLogger.cpp
Whoops. Seems I broke ZeroMQ on both the Windows and macOS builders, trying to use `std::string` with `zmq::message_t`. (In my defense, it works fine on Fedora 31! Must be a recent feature.)
I've reverted to the old `memcpy()` version of message construction, for all ZeroMQ versions.
=> ZeroMQ's std::string support is too new

src/FFmpegReader.cpp, tests/FFmpegReader_Tests.cpp
FFmpeg re-encoding algorithm don't uses `avg_frame_rate`.
=> Change frame rate detection

.gitlab-ci.yml
When merging #458 I somehow left an outdated command in the `.gitlab-ci.yml` Win64 command list that now references a nonexistent path, causing the build to fail.
=> Fix Win64 Gitlab builds

.travis.yml
A few things about our `.travis-ci.yml` file annoy their syntax checker. (This doesn't fix all of them, but the duplicate `addons.apt` sections I'm not sure we can fix currently.)
=> Make Travis' syntax checker happy(er)

CMakeLists.txt
This PR adds the debug-mode handling logic from the libopenshot-audio CMakeLists to the libopenshot build, ensuring that the two projects are build the same when built under the same circumstances.
(Juce's pickiness about having a `#define` for either `DEBUG` or `NDEBUG` in macOS builds also affects libopenshot, when the two libraries are being linked together, so it helps to have them both on the same page.)
=> Make debug handling match libopenshot-audio

include/ChunkReader.h, include/Clip.h, include/DummyReader.h, include/FFmpegReader.h, include/FrameMapper.h, include/ImageReader.h, include/QtHtmlReader.h, include/QtImageReader.h, include/QtTextReader.h, include/TextReader.h, include/Timeline.h, include/effects/Bars.h, include/effects/Blur.h, include/effects/Brightness.h, include/effects/ChromaKey.h, include/effects/ColorShift.h, include/effects/Crop.h, include/effects/Deinterlace.h, include/effects/Hue.h, include/effects/Mask.h, include/effects/Negate.h, include/effects/Pixelate.h, include/effects/Saturation.h, include/effects/Shift.h, include/effects/Wave.h
Turns out, some Clang++ versions are _much_ pickier than GCC, and will complain mightily about missing `override` annotations in derived classes. Because this is a header-file issue, the same set of warnings tend to repeat over, and over, and _over_ throughout the build.
This PR silences them all, with appropriate application of `override` wherever necessary.
=> Add all missing override markers on derived-class methods

.travis.yml
- Get rid of two-stage definition of apt.packages list, which was never necessary anyway.
- Remove deprecated `libavresample` from package set for FFmpeg 4
=> Travis: Fix package list syntax, contents

include/Exceptions.h
`pylint` pointed out that `BaseException` is a Python standard library exception class (not quite a reserved word, but pretty close), so it's not a great idea to redefine that name in our bindings. 
This PR renames it to `ExceptionBase`, which is actually more in keeping with our standard class naming system anyway. (Compare `ReaderBase`, `EffectBase`, `CacheBase`, etc.)
=> Rename our BaseException class to ExceptionBase, for Python

INSTALL.md
Fixed up the MarkDown a bunch, got rid of all those headings preceded by bullets (which are not legal markdown), and added some more possible CMake flags to the list (as well as cleaned up the existing ones and organized them into categories).
=> INSTALL.md: Formatting, markdown cleanup

version.sh
Just like OpenShot/libopenshot-audio#95, this adds a `version.sh` script at the root of the repo which extracts the `PROJECT_VERSION_FULL` string from `CMakeLists.txt`, and for the same reasons:
> This is useful for building libopenshot-audio as a Mac Homebrew `brew diy` project, which allows ad-hoc building of packages that install directly into the Homebrew environment.
> 
> e.g.
> ```sh
> $ cd libopenshot-audio
> $ cmake $(brew diy --name libopenshot-audio --version $(sh ./version.sh)) .
> [CMake runs with CMAKE_INSTALL_PREFIX set to $(brew --cellar)/libopenshot-audio/<version>/]
> $ cmake --build .
> $ cmake --build . --target install
> $ brew link libopenshot-audio
> ```
> ...and libopenshot-audio is linked into `/usr/local/opt/{lib,include}`.
> 
So, same thing with libopenshot: …
=> Add version.sh script

include/FFmpegUtilities.h
It is needed to avoid multiple definitions of AV_GET_CODEC_CONTEXT,
which is considered as an error with '-fno-common' which is default
since gcc-10.
Fixes: #511
=> FFmpegUtilities: replace variable definition with statement expression

include/Qt/AudioPlaybackThread.h, src/Frame.cpp, src/bindings/ruby/CMakeLists.txt
This is the companion PR to OpenShot/libopenshot-audio#97, and contains the fixes necessary in libopenshot's build to ensure that it works with a libopenshot-audio that wasn't built from our bundled JUCE sources.
(See that PR, as well as [Debian bug 925755](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925755), for background.)
In addition:
* Added some overlooked `juce::` prefixing, in places the unit tests don't touch (so it's not technically critical)
* Replaced our one use of `juce::ScopedPointer` (which is [deprecated](https://juce.com/discover/stories/coding-standards#object-lifetime-and-ownership)) with the recommended `std::unique_ptr` replacement.
=> Enable building with a libopenshot-audio that's based on non-bundled JUCE

src/Clip.cpp
This fix resolves issue: #419 
Clips are scale cropped in two places FFmpegReader.cpp and in Timeline.cpp:556.
FFmpegReader calculates the wrong size for scale with crop. It is because Timeline doesn't set clip for FFmpegReader (and for all readers) so FFmpegReader doesn't now anything about SCALE_CROP, because it is a property of Clip.
And in FFmpegReader in line 1396 (in the last version) Clip *parent = (Clip *) GetClip();
We get parent = NULL and so it doesn't check scale property and calculate sizes using default formulas which are incorrect for SCALE_CROP case (and may be for SCALE_FIT and SCALE_STRETCH too).
I'll post some before and after screen-grabs just now but this change fixes the issue with 1:1 video scaling/cropping.
=> Set clip in constructor to resolve scale crop issue

src/bindings/ruby/CMakeLists.txt
I used `add_compile_definitions()` in #515, which is CMake 3.12+ only. (Oops.) Switch to `add_definitions()` which has been supported since the dawn of time.
=> Fix support for older CMake

include/Clip.h, src/Clip.cpp, src/Timeline.cpp
Adding keyframable origin point (for shear and rotation). Used in https://github.com/OpenShot/openshot-qt/pull/3366. Both rotation and shear use an origin point to control how those tools work. This allows the user to not only set a custom origin point (as a % of the original clip), but it allows the origin to be animated, which allows for some really great animations!
origin_x: **0.0** = left side of clip
origin_x: **1.0** = right side of clip
origin_y: **0.0** = top side of clip
origin_y: **1.0** = bottom side of clip
=> Transform Improvements (Keyframe origin point)

.travis.yml
Temporarily set the FFmpeg 3.2 build as "allowed to fail", while we work out what to do about its suddenly-private PPA.
=> Travis: allow_failures for FFmpeg 3.2

.travis.yml, src/bindings/ruby/CMakeLists.txt
Travis appear to have quietly brought up Ubuntu Focal as an available build `dist` (still undocumented anywhere, AFAICT). Still, using an undocumented Travis environment is the lesser evil, vs. using FFmpeg packages from a community PPA that's already bailed on us once.
=> Travis: Switch to Ubuntu 20.04 Focal for FFmpeg 4 build

.travis.yml, src/FFmpegWriter.cpp
Fix FPS setting on FFmpeg 4, which currently is not setting a valid FPS. This causes all sorts of strange behavior on videos produced with libopenshot using FFmpeg 4. This patch does require a depreciated approach, and I'm not sure how we are supposed to be correctly setting the FPS parameter, so I'm open to suggestions.
Also, thanks to PeterM for troubleshooting this issue and finding a solution! Nice work!
=> Fix FPS setting on FFmpeg 4

src/FFmpegWriter.cpp
Initial changes to include new codecs
=> Newer codecs (svt_av1, rav1e, svt_hevc)

include/DummyReader.h, src/DummyReader.cpp, src/Frame.cpp, tests/CMakeLists.txt, tests/DummyReader_Tests.cpp
Adding the ability to add test frames `WriteFrame()`, with fake image and audio data. This will can be used in unit-tests, and will soon be used to verify some new audio improvements (coming soon).
=> Adding some new functionality and documentation to DummyReader

include/FFmpegWriter.h, src/FFmpegWriter.cpp
WIP: Changing some libopenshot code based on Codacy feedback. Small refactoring, scope limiing.
=> WIP: Changing some libopenshot code based on Codacy feedback

src/FFmpegWriter.cpp
New codec are now handled better, i.e. libaom-av1 has now settings that allow a usable encoding speed. The settings for rav1e and svt-av1 were adjusted to.
When a bitrate is selected, which is not supported by the av1 encoders (yet), a reasonable quality setting is chosen.
=> Improvements to handling of new codecs

include/MagickUtilities.h
Stupid ImageMagick 6 has a code boner in its header files that produces warning messages at every `#include`, if `-Wextra` is enabled during build:
```
In file included from /usr/include/ImageMagick-6/magick/memory_.h:22,
from /usr/include/ImageMagick-6/magick/MagickCore.h:125,
from /usr/include/ImageMagick-6/Magick++/Include.h:45,
from /usr/include/ImageMagick-6/Magick++.h:10,
from /home/ferd/rpmbuild/REPOS/libopenshot/worktree-valgrind/include/Qt/../MagickUtilities.h:39,
from /home/ferd/rpmbuild/REPOS/libopenshot/worktree-valgrind/include/Qt/../Frame.h:56,
from /home/ferd/rpmbuild/REPOS/libopenshot/worktree-valgrind/include/Qt/../RendererBase.h:34,
from /home/ferd/rpmbuild/REPOS/libopenshot/worktree-valgrind/include/Qt/VideoRenderer.h:34,
from …
```
=> MagickUtils: Add #pragma to silence IM6 warning

src/FFmpegWriter.cpp
The values for qmax and qmin were set for all codec but only mpeg2 needed them and as a result the bitrates of the exported clips could be wrong. Now only when the export is with mpeg2 the default values are changed.
=> Bitratecorrect

include/DummyReader.h
Using DummyReader with a custom cache with a Timeline can lead to
strange exceptions due to Timeline's buffering.  Therefore adding a
note to the DummyReader documentation about that.
See #532
=> Add a note about the buffering behavior of Timeline to DummyReader

.gitlab-ci.yml, CMakeLists.txt, include/OpenShotVersion.h.in, src/CMakeLists.txt, tests/CMakeLists.txt
The CMake process will pick up Qt's `Qt5Core_VERSION_STRING` variable and stick it in the CMake cache (with forced updating each run). A new `#define` in the header exports that as `QT_VERSION_STR` to both the library and the Python bindings. That way it can be queried at runtime, same as PyQt5's versioning:
```python3
>>> import openshot
>>> print(openshot.QT_VERSION_STR)
5.13.2
>>> from PyQt5 import Qt
>>> print(Qt.QT_VERSION_STR)
5.13.2
>>> print(Qt.PYQT_VERSION_STR)
5.13.2
```
**Edit:** I added a few more:
```python3
>>> openshot.AVUTIL_VERSION_STR
'56.31.100'
>>> openshot.AVCODEC_VERSION_STR
'58.54.100'
>>> openshot.AVFORMAT_VERSION_STR
'58.29.100'
>>> openshot.HAVE_IMAGEMAGICK
1
>>> openshot.HAVE_RESVG
1
```
**Edit2:** One more:
```python3
>>> openshot.APPIMAGE_BUILD
0
```
It's …
=> Add version/feature #defines to OpenShotVersion.h

src/CMakeLists.txt
Should fix #510 breakage on gitlab builders.
=> Enable IN_LIST in older CMake

src/CMakeLists.txt
As a followup to #540 which removed the `find_package(Threads REQUIRED)` call and subsequent use of the `Threads::Thread` target, this PR eliminates the two legacy CMake variables that we were configuring immediately previous. It seems less problematic to simply let OpenMP handle all this for itself, something it appears perfectly capable of doing now.
=> CMake: Remove threading config variables

.travis.yml
The PPA we were using for our FFmpeg 3.2 test builds is gone, and since there's no currently-supported Ubuntu release with 3.2 available there's no reliable way to get it back. Time to just drop it from the build matrix again, building with community PPAs has proven too unreliable to go back down that road. We still have builds in one version each of FFmpeg 2, 3, and 4.
=> Remove FFmpeg 3.2 from Travis matrix

src/CMakeLists.txt
Turns out, we don't actually use any of the classes in QtMultimedia (or its Widgets), so this PR drops them as dependencies.
This also prevents both Qt5Network and Qt5OpenGL getting pulled in as dependencies, and reduces our Qt dependency fingerprint significantly to just the three modules (now) listed in the `CMakeLists.txt`: QtCore, QtGui, and QtWidgets.
Shared libs being what they are, it only reduces the final size of `libopenshot.so` by about 33Kb, but the size isn't the point. (Besides, not loading four big Qt modules could give runtime a teeny tiny bit more pep, theoretically.)
```console
$ ldd libopenshot.so.0.2.5 |& grep -i qt
libQt5MultimediaWidgets.so.5 => /lib64/libQt5MultimediaWidgets.so.5 (0x00007f8911972000)
libQt5Widgets.so.5 => /lib64/libQt5Widgets.so.5 …
```
=> Drop QtMultimedia and QtMultimediaWidgets deps

tests/Settings_Tests.cpp
The Settings test attempts to test the class by changing settings variables and reading them back again. Problem is, that affects the REST of the unit tests.
So instead of changing `HARDWARE_ACCEL` (accidentally enabling HW accel and causing test failures), we'll diddle something more innocuous, like `OMP_THREADS`.
=> Tests: Don't enable HW accel as side-effect

src/effects/Pixelate.cpp
Fixes: https://github.com/OpenShot/libopenshot/issues/506
=> Improve Pixelate filter scale

include/FFmpegUtilities.h, src/FFmpegWriter.cpp
By default, the 4:2:0 is used, that is not lossless itself. Thus, even if crf=0 was set - the loss of the color info still occurs. This change is step to fix it.
This is part of the: https://github.com/OpenShot/libopenshot/pull/219
=> Use non-subsampled color format for lossless encoding with the h264 encoder

include/Clip.h, include/ReaderBase.h, include/Timeline.h, src/Clip.cpp, src/FFmpegReader.cpp, src/QtImageReader.cpp, src/ReaderBase.cpp, src/Timeline.cpp, tests/Timeline_Tests.cpp
This PR adds two things to Timeline, primarily intended for use by OpenShot:
1. A lookup API to retrieve Clips, timeline Effects (transitions), and Clip Effects singly by `Id` string lookup
1. A `GetMaxTime()` that computes the time the last clip/effect ends and returns it as a `double` whole-and-partial-seconds value, and a `GetMaxFrame()` that returns the same thing accounting for frame rate as an `int64_t` frame number.
Full unit tests are included for `Timeline::GetMaxFrame()/Timeline::GetMaxTime()`, `Timeline::GetClip()`, `Timeline::GetTimelineEffect()`, and `Timeline::GetClipEffect()`. The `Clip::GetEffect()` implementation isn't unit-tested directly, but it is used by `Timeline::GetClipEffect()` so it's tested indirectly.
Along the way, I also deprecated `ReaderBase::GetClip` and …
=> Timeline: Add clip/effect lookup api, GetMaxFrame/GetMaxTime method (w/ unit tests)

include/CacheDisk.h, include/QtUtilities.h, src/CacheDisk.cpp
Recent Qt releases complain about `endl` being used to terminate `QTextStream` lines, and recommend using `Qt::endl` instead. So, let's.
=> Use Qt::endl with QTextStream

src/FFmpegReader.cpp
Use the calculated `0 - PTS`, unless it is too large (more than 1 second off from zero). This is related to a previous PR (with much discussion): https://github.com/OpenShot/libopenshot/pull/311. This PR fixes the regression related to limiting the offset, and I think makes more sense than previous suggestions. 
The PTS offset was always designed as a quick way to "zero" out the video PTS and audio PTS values, so we could calculate frame numbers, based on the starting PTS values, etc... But in my testing, some videos are encoded with negative timestamps, especially common with audio tracks, where the audio starts before the 1st video frame. OpenShot is not really designed to deal with this, and it causes us to search for matching packets which never come. This could/does introduce some …
=> Fix the PTS offset logic error when first reading a file with FFmpegReader

src/FFmpegWriter.cpp
With the official inclusion of SVT-AV1 the library changed from svt_av1 to svtav1. This takes this into account
=> Change of name of library

src/FrameMapper.cpp
Apparently, we need enough padding during resampling, so we exceed the # of samples required for the first frame, and 20 was just too low for many frame rates / sample rates. This seems kind of random / arbitrary, but it's an easy fix for a more complex issue, where resampling always leaves behind some samples for the next call, and we can really mess up our sample division logic.
=> FrameMapper + Resampling loses samples

include/FrameMapper.h, src/FrameMapper.cpp, src/Timeline.cpp, tests/FrameMapper_Tests.cpp
Implemented position remapper inside FrameMapper to fix audio noise when exporting to different fps
The FrameMapper class now receives the updated clip position and returns the correct amount of samples for a given frame number.
=> Implemented position remapper inside FrameMapper to fix audio noise when exporting to different fps

src/FFmpegWriter.cpp
The field order of the interlaced frames is set. This is only a very rude version.
More work needs to be done
=> Set the field order when interlace is on

include/FFmpegReader.h, include/FFmpegWriter.h, include/OpenMPUtilities.h, include/Timeline.h, src/FFmpegReader.cpp, src/FFmpegWriter.cpp, src/Timeline.cpp
This was primarily inspired by Codecov flagging some code as unreachable, turned out it has a bit of history. But this corrects that, moves us off of a deprecated OpenMP API call, and makes some tweaks to FFmpegWriter/Reader along with Timeline, while I was touching them.
I'll explain some of the changes in inline comments.
=> Move off deprecated OpenMP API, fix FFmpeg code paths

include/ImageReader.h, include/QtImageReader.h, src/ImageReader.cpp, src/QtImageReader.cpp, tests/ImageWriter_Tests.cpp
`ImageWriter.cpp` was literally _one line_ of code away from full coverage, so I wrote a `CHECK_THROW()` test for that one line (an exception).
I also added `CHECK_THROW()`s for two exceptions in `ImageReader.cpp`, and performed the same constructor consolidation trick on it that I used for FFmpegReader (make `inspect_reader` an optional arg with a default value of true, instead of having two overloads, one with and one without). That should complete the coverage of every method in ImageReader _except_ for the `Json::Value`-form setter and getter.
=> Tests: Increase coverage for ImageReader, 100% for ImageWriter

codecov.yml, tests/Color_Tests.cpp, tests/FrameMapper_Tests.cpp, tests/Point_Tests.cpp
**Update**: I'm an idiot. The failure was due to the short duration, and the fact that there were only 120 frames _available_ in the reader at the specified frame rate. (Though, interestingly, that _doesn't_ throw an `OutOfBoundsFrame` it seems.)
<s>As it says, this PR is a work-in-progress. Not because it's unfinished, but because a test is failing.</s>
I decided to replace the first test (which had a `catch` in it that was screwing up the test coverage) with a simple no-op test: Create a mapping from 24fps to 24fps with no pulldown. Then read its `Name()` (adds an extra line of coverage), and finally read one frame from it. So, it just gets the same frame back. (When you use the right duration.)
<s>Unfortunately, **the test _fails_**, and gets back frame `120` for original frame `125`. …
=> Various unit tests: Increase coverage

codecov.yml
I realized we were trying too hard. According to the expansion returned by their validator,
```yml
ignore:
- "examples/**/*"
- "bindings/**/*"
```
translates to:
```json
{
"ignore": [
"(?s:examples/.*/[^\\/]+)\\Z",
"(?s:bindings/.*/[^\\/]+)\\Z"
]}
```
Which will ignore all files _two_ levels below `examples` and `bindings`, but won't ignore any files _directly_ inside either dir.
=> codecov.yml: Update ignore list

src/Clip.h, src/ImageReader.h, src/QtHtmlReader.h, src/QtImageReader.h, src/QtTextReader.h, tests/ImageWriter_Tests.cpp
This PR fixes the return type for `GetCache()` in various readers, and fixes some Clip methods that were missing `override`.
=> Overrides and types

bindings/python/openshot.i, bindings/ruby/openshot.i, src/Timeline.cpp, src/Timeline.h
Fixing an issue caused by timeline::GetClip returning a ClipBase instead of a Clip (broke waveform generation). 
Also adding a swig definition for the Caption effect.
=> Fixing an issue caused by timeline::GetClip returning a ClipBase* instead of Clip*

tests/Timeline_Tests.cpp
Defense against any recurrence of #595 breakage.
=> Timeline::GetClip: Add anti-slicing checks to unit tests

codecov.yml
The `base` argument to `coverage.status.project.<name>` is now deprecated, and AFAICT `codecov.branch` just doesn't exist as a parameter; it looks like I just made it up or something.
Hoping this will fix the repo's Dashboard display on Codecov's site always showing no data.
=> Refresh Codecov configs

src/OpenMPUtilities.h
It's a good thing very-new OpenMP implementations aren't that common yet, as I got the function name used for thread-count lookup completely wrong. Correcting.
=> Correct OpenMP function name

tests/Cache_Tests.cpp, tests/Clip_Tests.cpp, tests/Color_Tests.cpp, tests/Coordinate_Tests.cpp, tests/DummyReader_Tests.cpp, tests/FFmpegReader_Tests.cpp, tests/FFmpegWriter_Tests.cpp, tests/Fraction_Tests.cpp, tests/Frame_Tests.cpp, tests/ImageWriter_Tests.cpp, tests/KeyFrame_Tests.cpp, tests/Point_Tests.cpp, tests/ReaderBase_Tests.cpp, tests/Settings_Tests.cpp, tests/Timeline_Tests.cpp
To prevent slow compiles of unit tests, this PR replaces all of the `#include "OpenShot.h"` invocations with includes of the individual headers actually needed by each test file. This has little effect on files like `Clip_Tests.cpp` and `Frame_Tests.cpp`, but **hugely** speeds up the compilation (and reduces the size) of files like `Coordinate_Tests.cpp` and `Fraction_Tests.cpp`.
=> Unit tests: Don't use OpenShot.h header

src/FFmpegReader.cpp, src/FFmpegUtilities.h
This is a regression from using premultiplied colorspace in Qt. If a video has an alpha channel, we need to convert the RGBA correctly to premultiplied (which is slower), but without the conversion, all the alpha values are wildly wrong.
=> Fix videos with alpha channel

src/Timeline.cpp
Reverting 'clear the cache when the user seeks' experiment. It was a failed experiment, not to mention that it destroys performance on the "Transform" tool. In theory, I was worried about boundaries between seek blocks. But I think having some inconsistent moments between blocks of separately decoded frames is okay during a real-time preview scenario. When final render is happening, we don't seek randomly around, and so this is not a problem.
=> Revert cache-busting-on-seek Experiment

src/CMakeLists.txt, src/protobuf_messages/CMakeLists.txt
Changing name of ProtoBufMessage to openshot_protobuf for clarity, also installing it in PREFIX/lib. Also, versioning the same as libopenshot, so we don't get conflicts between releases and updates to the protobuf message types.
=> Fixing INSTALL issue related to ProtoBufMessage.dylib

bindings/python/CMakeLists.txt, bindings/ruby/CMakeLists.txt, cmake/Modules/FindResvg.cmake, src/CMakeLists.txt
I suspect since the bindings were moved out of the `src/` directory, the `CMAKE_SWIG_FLAGS` haven't been propagating to the `swig` command line that generates the wrapper script. This means that the `#ifdef`s in the `openshot.i` files are all interpreted wrong.
This PR adds generator expression logic to copy _every_ public compile definition from the `openshot` library target over to the `SWIG_FLAGS` of the `openshot.i` file, which should ensure that the bindings are generated correctly.
In my version of CMake, all compile definitions are stored in the target property _without_ the leading `-D`, even if it was originally set. So, the generator expression I added will prepend `-D` to each of the values. I'll have to check whether that holds for older CMake versions as well, otherwise we …
=> Propagate library defs to swig

src/FFmpegUtilities.h
Improved detection of AVPixelFormat containing Alpha channel, I'm going with a simple list. Not sure if this will work well with older versions of FFmpeg though, as these items change over time. Waiting to see how build servers handle it.
=> Improved Detection of AVPixelFormat containing Alpha channel

src/FFmpegUtilities.h
Related to https://github.com/OpenShot/libopenshot/pull/609. Implementing a much improved alpha channel detection method, which works on all formats that contain an alpha channel. Shout out to @ferdnyc for the suggestion!
=> Thanks to @ferdnyc for the suggestion to better detect alpha channels.

src/effects/Bars.h, src/effects/Blur.h, src/effects/Brightness.h, src/effects/Caption.h, src/effects/ChromaKey.h, src/effects/ColorShift.h, src/effects/Crop.h, src/effects/Deinterlace.h, src/effects/Hue.h, src/effects/Mask.h, src/effects/Negate.h, src/effects/Pixelate.h, src/effects/Saturation.h, src/effects/Shift.h, src/effects/Wave.h
This PR tweaks the `GetFrame(int64_t frame_number)` overload in each effect from:
```c++
std::shared_ptr<openshot::Frame> GetFrame(int64_t frame_number) override {
return GetFrame(std::shared_ptr<Frame> (new Frame()), frame_number);
}
```
to:
```c++
std::shared_ptr<openshot::Frame> GetFrame(int64_t frame_number) override {
return GetFrame(std::make_shared<openshot::Frame>(), frame_number);
}
```
In accordance with #556, which did the same for other instances of shared-pointer creation. Extended rationale there.
=> Effect GetFrame(): Use std::make_shared

src/effects/ObjectDetection.cpp, src/effects/Stabilizer.cpp, src/effects/Tracker.cpp
The new effects were picking up the definition of `InvalidJSON` from one of the other headers, which no longer `#include "Exceptions.h"`. So, they should include it directly.
=> Add Exceptions.h include to new effects

.github/workflows/ci.yml
Make sure our CI runs are built with OpenCV and Protocol Buffers enabled.
=> Add Protobuf and OpenCV to CI preinstalls

bindings/python/openshot.i, src/KeyFrame.cpp, src/KeyFrame.h
Hopefully this will fix the SWIG build on launchpad.
=> KeyFrame.h: Avoid shadowing SWIG templates

src/OpenShot.h
I hadn't actually intended to remove `#include "Exceptions.h"` from `OpenShot.h`, that was an overzealous find-and-replace on my part. I'm fine with `OpenShot.h` being the only header that _does_ automatically include it, even though for most practical applications I feel `OpenShot.h` is now far too heavy to actually use.
(Our own unit tests have stopped using it in favor of targeted includes, for example, because it'd been building in this direction for a while, and OpenCV was the tipping point on `#include "OpenShot.h"` bringing in way too much stuff and excessively slowing down each source file's compilation. Still, for convenience it's "fine", and should include the exception definitions as well.)
=> Add Exceptions.h back to OpenShot.h

bindings/python/openshot.i, src/KeyFrame.cpp, src/KeyFrame.h, tests/KeyFrame_Tests.cpp
I screwed up the slot name for Fraction's string representation (`__str__` not `__string__`, dummy!), so this PR fixes that.
It also gets rid of the `Keyframe(std::vector<Coordinate>)` constructor, which as SWIG points out in an emitted warning will shadow `Keyframe(std::vector<Point>)` or vice versa, and the `Point` version is far more useful. The aliased names for the arguments are also removed, on the off chance they're part of what's messing up SWIG on Ubuntu 16.04.
=> Tweak the Python bindings for KeyFrame, Fraction

src/QtImageReader.cpp
Switching to QImageReader for parsing a path to a QImage, and allowing the AutoTransform property correctly handle exif metadata (flipping and orientation of images)
=> Support for auto-rotation of Image Exif metadata

.gitlab-ci.yml
Adding make threads to libopenshot-audio and libopenshot, to increase speed of compilation. Related to https://github.com/OpenShot/libopenshot-audio/pull/115.
Speed comparisons:
- libopenshot (linux): 5 minutes 9 seconds -> 2 minutes 14 seconds  (2.3 times faster)
- libopenshot (mac): 5 minutes 25 seconds -> 1 minute 20 seconds (4 times faster)
=> Experimental multi-thread builds for Linux and Mac

.github/workflows/ci.yml
A message in their UI seemed to indicate it would make our data show up (it hasn't been, on their site).
=> Add CODECOV_TOKEN envvar to Github CI

.gitignore, examples/Example.cpp, examples/qt-demo/main.cpp, src/CMakeLists.txt, src/Clip.cpp, src/Clip.h, src/ClipBase.h, src/FFmpegReader.cpp, src/FFmpegReader.h, src/FFmpegWriter.cpp, src/Frame.cpp, src/KeyFrame.cpp, src/Qt/VideoCacheThread.cpp, src/Qt/VideoCacheThread.h, src/QtPlayer.cpp, src/Settings.cpp, src/Settings.h, src/Timeline.cpp, src/Timeline.h, src/ZmqLogger.cpp, tests/Clip_Tests.cpp, tests/Settings_Tests.cpp
After some extensive profiling using a variety of tools, we have found a few interesting and actionable issues. Bottom line, OpenMP is not actually providing us any improvement where we need it, and instead, it's adding additional overhead, by spinning up many threads, waiting for threads to finish, shutting down threads, etc... 
Related openshot-qt PR: https://github.com/OpenShot/openshot-qt/pull/4012
**Improvements:**
- I've removed **OpenMP** from `Timeline`, `FFmpegReader` classes. These are now optimized to return the first matching frame as quickly as possible (no more attempting to process a bunch of Frame instances in multiple threads).
- I've refactored Clip::GetFrame, including an override that allows the Timeline to pass in the current Frame (to be used as a background image). …
=> Huge performance improvements (43% faster FFmpegReader, 34% faster Timeline)

.gitlab-ci.yml, CMakeLists.txt
Improving the git log format to be consistent across all 3 repos, and adding VERSION and SO data into our version file (used by our release automation).
=> Git log improvements (for consistency) + Release flow improvements

src/effects/ChromaKey.cpp
Each channel must be updated, vs just the alpha value. This is a result of the alpha value already multiplied into the R,G,B, so this leaves behind darker pixels and artifacts, if we don't zero all these pixels out.
=> Chromakey fix for pre-multiplied Alpha

.github/workflows/ci.yml
Honestly thought I'd already committed this, but I guess I was thinking of #636.
When used with Github Actions and its predefined `actions/checkout` step, Codecov needs the depth overridden in the default `git checkout --depth=1` command, which can be done by explicitly setting a `fetch-depth` option for `actions/checkout`. This PR changes that step to:
```yml
steps:
- uses: actions/checkout@v2
with:
fetch-depth: 0
```
See https://community.codecov.io/t/issue-detecting-commit-sha-please-run-actions-checkout-with-fetch-depth-1-or-set-to-0/2571
=> Set checkout fetch depth for codecov

src/FFmpegReader.cpp
The only reason an `AV_ALLOCATE_FRAME()` could fail is because
there wasn't enough memory to allocate the necessary buffers,
so if it returns a `nullptr` then throwing `OutOfMemory` makes
far more sense than throwing `OutOfBoundsFrame`.
Related to https://github.com/OpenShot/libopenshot/issues/644#issuecomment-799766354
=> FFmpegReader: Throw correct exception

src/CVObjectDetection.cpp, src/CVStabilization.cpp, src/CVTracker.cpp, src/FFmpegWriter.cpp, src/FrameMapper.cpp, src/FrameMapper.h, src/effects/Stabilizer.cpp, src/effects/Tracker.cpp, tests/FrameMapper_Tests.cpp
Added new unit test which distributes audio samples between many different frame rates (30/1, 24/1, 30000/1001, 119/4), and fixes a huge issue with mapping frame numbers incorrectly causing audio crackles/pops. Also fixes a bug which causes crashes on NON-STEREO channel layouts.
For example, when using a source video with a 119/4 frame rate (29.75 fps) and converting it to 30 fps (and positioning the Clip at position 3.77 seconds), it would generate a huge amount of high frequency pops, due to incorrect frame # adjustments inside FrameMapper.
=> FrameMapper Audio Crackles/Popping Fixes

examples/Example.cpp, src/Timeline.cpp, src/Timeline.h, tests/Timeline_Tests.cpp
This PR was inspired when I read this line in the latest `Example.cpp`:
```cpp
Timeline tm(r9.info.width, r9.info.height, r9.info.fps, r9.info.sample_rate, r9.info.channels, r9.info.channel_layout);
```
"Well, that's not using the compiler very efficiently.", I thought to myself. "Nobody should ever have to type that line more than once."
So, I typed that line once, as a new delegating constructor for the `Timeline` class. Its entire code:
```cpp
Timeline::Timeline(const ReaderInfo info) :
Timeline::Timeline(info.width, info.height, info.fps, info.sample_rate,
info.channels, info.channel_layout) {};
```
As a result, that line in `Example.cpp` becomes:
```cpp
Timeline tm(r9.info);
```
And effectively, the compiler transforms it into the code that used to be there. Easy-peasy. A new unit …
=> Timeline: Add a new constructor that takes a ReaderInfo struct and copies parameters

CMakeLists.txt, tests/CMakeLists.txt
This PR fixes builds on systems where Catch2 is not available, by simply skipping the unit tests build entirely.
=> Properly handle unavailable Catch2

CMakeLists.txt, tests/CMakeLists.txt
I got my variable names crossed juggling recent PRs, and committed code that accidentally disabled all of the unit tests. Fixing so they run again.
=> CMake: Properly enable unit tests

tests/CMakeLists.txt
Just like the OpenCV tests require OpenCV, the ImageWriter tests require that ImageMagick be enabled in the build. If it isn't, skip those tests entirely. Silences a CTest message correctly complaining that the unit test executable "has no tests!", when not linked with ImageMagick.
=> tests: Make ImageWriter tests dependent on ImageMagick being enabled

CMakeLists.txt, tests/CMakeLists.txt, tests/KeyFrame.cpp, tests/Point.cpp
Each unit test file <code><var>ClassName</var>.cpp</code>, which results in the creation
of a test target <code>openshot-<var>ClassName</var>-test</code>, will now also be labeled
with the CTest label <code><var>ClassName</var></code>, and a target <code><var>ClassName</var>_coverage</code> will be generated that runs only the tests in that file.
Just like the main `coverage` target, the target name <code><var>ClassName</var>_coverage</code> is just a generic name. Running the target will collect coverage data if `ENABLE_COVERAGE` is set, but will run the tests without coverage if it is left disabled. It does not imply collection of coverage data.
The separate targets are especially useful when developing tests for a class, as the tests in the class being worked on can be re-run without …
=> CMake: Add separate unit test targets

src/CMakeLists.txt
I misread the CMake docs, and didn't realize that `SEND_ERROR` message severity would still register as a failed config at the end of the run. So, OpenCV 4.5.1 is still killing our Ubuntu Impish PPA builds.
Downgrade to `WARNING` to let them succeed.
=> Downgrade OpenCV 4.5.1 msg to WARNING

.gitlab-ci.yml
The Gitlab builders have been writing metadata into a file named `<installpath>/share/<reponame>` which is impossible to glob for. So, rename all those files to `<installpath>/share/<reponame>.env`.
=> Rename build environment files so we can glob for them

src/CMakeLists.txt
We don't actually use ImageMagick's MagickWand API at all, ditto for ffmpeg's avdevice, avfilter, or postproc. We also don't use avresample, except when swresample is unavailable. So, this PR pares down the modules we _do_ link with and depend on to just the set we actually use.
Also, when using the _bundled_ jsoncpp, building it as an `OBJECT` target saves us from having to recompile it for each target it's linked to. (Which will save a lot of time, especially now that each unit test class is a separate target. Number of times jsoncpp is compiled during the build goes down from 26 to just 1.)
=> Reduce dependencies by eliminating unnecessary components

.github/workflows/ci.yml
Seems Github Actions broke their Ubuntu bionic build image recently, making the libzmq3-dev apt install fail. Adding a workaround. See actions/virtual-environments#3317.
=> CI,bionic: Work around broken libzmq5 dep

src/effects/Bars.cpp, src/effects/Caption.cpp, src/effects/ChromaKey.cpp
In `Clip::PropertiesJSON`, the root of the `wave_color` node was created referencing the `red` `Keyframe`:
```c++
root["wave_color"] = add_property_json("Wave Color", 0.0, "color", "", &wave_color.red, 0, 255, false, requested_frame);
root["wave_color"]["red"] = add_property_json("Red", wave_color.red.GetValue(requested_frame), "float", "", &wave_color.red, 0, 255, false, requested_frame);
root["wave_color"]["blue"] = add_property_json("Blue", wave_color.blue.GetValue(requested_frame), "float", "", &wave_color.blue, 0, 255, false, requested_frame);
root["wave_color"]["green"] = add_property_json("Green", wave_color.green.GetValue(requested_frame), "float", "", &wave_color.green, 0, 255, false, requested_frame);
```
(Note, specifically, the `&wave_color.red` passed as the fifth argument to …
=> Fix counting of points for color effects

src/CVObjectDetection.cpp, src/TrackedObjectBBox.cpp, src/effects/ObjectDetection.cpp, src/effects/Tracker.cpp
Changed JSON communication for detected objects
- The OBjectDetection and Tracker effects have a key "objects" in the Json that contains a dictionary of TrackedObjectBBox indexed by the object ID
- self.data now keep track of all changes in detected objects
Example of the JSON for ObjectDetection:
```
{ // effect parameters
"id": 7QCETIYKEJ
"selected_object_index": "2"
"confidence_threshold": "0.5"
"class_filter": "truck"
"objects":{
//these are the detected objects dicts
"9FDETJYKEJ":{
"box_id" : "9FDETJYKEJ"
"x1": "50"
"y1": "50"
"x2": "100"
"y2": "100"
"delta_x": {...}
...
}
"56BR38F17U":{
"box_id" : "56BR38F17U"
"x1": "50"
"y1": "50"
"x2": "100"
"y2": "100"
"delta_x": {...}
...
}
}
}
```
=> Changed JSON communication for detected objects

src/Clip.cpp, src/Clip.h, src/Timeline.cpp, src/Timeline.h, src/TimelineBase.h
Refactor of global timeline effects, to address a regression with global/timeline Mask/Transitions no longer working correctly. This was caused by an optimization that broke the general behavior of the global transitions.
=> WIP: Fix Mask/Transitions for Global Timeline Effects

CMakeLists.txt
(No wonder I couldn't find this PR, I opened it in my _fork_. Oy.)
Linking OBJECT libraries into SHARED targets (a trick to avoid recompilation of the bundled jsoncpp) means the build fails on all CMake versions through 3.11.
(Originally discussed via email. Solved on the project builders by @jonoomph, with an upgrade to CMake 3.20.2 on Linux. Windows was already on 3.20.1 following MSYS2 update, macOS is running 3.19.1.)
Technically CMake versions earlier than 3.12 will work _**if**_ a precompiled system jsoncpp is used, but I'd rather only declare compatibility with versions for which we maintain unqualified support.
=> CMake: Set minimum version to 3.12

src/Clip.cpp
2cf2c55f was a bit too ambitious, and swept away all of the property value choice labels that used to contain `"None"`.
cc: @BrennoCaldato
=> Clip: Restore property choice names

bindings/python/CMakeLists.txt, bindings/ruby/CMakeLists.txt
**(F---ING _FINALLY!!!_)**
Mostly a developer convenience, when building using the newest CMake 3.20 or later, the SWIG targets will be configured with `USE_SWIG_DEPENDENCIES` set to `TRUE`, which causes the target to automatically set up dependencies on all of the files referenced by the SWIG bindings.
Which means, when you make changes to `Frame.h` or `Clip.h` or whatever, the bindings will be automatically regenerated, and you no longer have to `rm -r build/bindings` in order to force a re-sync with the header files.
=> CMake: USE_SWIG_DEPENDENCIES for CMake 3.20+

src/CMakeLists.txt, src/FFmpegUtilities.h, src/OpenShotVersion.h.in
:heavy_check_mark:  <s> **Note: PR #694 MUST be merged before this PR.** </s>
I discovered with @BrennoCaldato 's help that having CMake decide which resampling library to link with, but having the code in the `FFmpegUtilities.h` header decide which one to _use_, wasn't really working out well in all cases. In some FFmpeg versions, CMake would link with libswresample, but the header would select the avresample API, resulting in a broken libopenshot build that didn't have the right set of library dependencies configured.
This PR moves the determination as to which resampling library to use into the `src/CMakeLists.txt` code, which will set flags to _tell_ `FFmpegUtilities.h` which one has been linked in (and therefore, which one to use). This ensures no broken builds due to mismatching …
=> FFmpeg: Move av/swresample decision into CMake

src/FFmpegWriter.cpp
AVFrame was missing a few properties that need to be set in newer versions of FFmpeg. This is also compatible with FFmpeg 3+, based on my testing.
Closes: https://github.com/OpenShot/libopenshot/issues/676
=> Fix audio encoding on FFmpeg 4+

src/Clip.cpp
Changing rotation data assumed that a video file's starting rotation is 0 degrees.
This change allows users to set a 0 degree keyframe when there is only one rotation keyframe.
=> Only get rotation from metadata if 0 keyframes

src/CMakeLists.txt
At some point along the way, support for `-DENABLE_MAGICK=0` got broken in CMake. This restores it.
=> CMake: Fix ENABLE_MAGICK

src/FFmpegUtilities.h
Turns out, `const` is ignored on a `bool` return type from a `static` function. With a high enough warning level, gcc will even tell you about it. (Which gets REALLY annoying, as this file is included in lots of places.)
=> Eliminate useless 'const'

src/Clip.cpp, src/FFmpegReader.cpp, src/QtImageReader.cpp, src/QtImageReader.h, tests/QtImageReader.cpp
Since OpenShot changes the preview window size during editing, the SCALE_NONE clips should always be scaled to the ratio: `preview width / timeline width`... so they stay relative sized to the timeline size.
For example, if an SVG is 500px wide, and the project is 1000px wide... the SVG in SCALE_NONE mode should always be 50% with width of the video, regardless of how small you make the preview window.
=> SCALE_NONE was incorrectly sizing SVG, Image, and Video files.

tests/CMakeLists.txt
Newer versions of Catch2 require C++14 to compile, a requirement that won't be propagated to the object library unless we link it to the IMPORTED Catch2::Catch2 target.
Fixes #707 (I _believe_)
=> Link catch-main wtih Catch2::Catch2

src/effects/Crop.cpp, src/effects/Crop.h
Adding an X and Y offset to the current crop effect, to better support previous clip crop parameters (for migrating crop options from OpenShot 2.5.1 to OpenShot 2.6). Also refactoring the crop effect, to actually copy the pixels into a new image buffer.
Below are my notes I used to come up with this logic (for anyone curious what kind of mental juggling is required for this):
```
0 1 2 3 4 5 6 7 8 9 10
0 1 2 3 4 5 6 7 8 9 10
0 1 2 3 4 5 6 7 8 9 10
0 1 2 3 4 5 6 7 8 9 10
0 1 2 3 4 5 6 7 8 9 10
0 1 2 3 4 5 6 7 8 9 10
0 1 2 3 4 5 6 7 8 9 10
0 1 2 3 4 5 6 7 8 9 10
0 1 2 3 4 5 6 7 8 9 10
0 1 2 3 4 5 6 7 8 9 10
0 1 2 3 4 5 6 7 8 9 10
0 1 2 3 4 5 6 7 8 9 10
1) Apply the bounds (DEST start + length)
DEST START == SRC START
LENGTH == CROPPED-WIDTH
2 3 4 5 6 7 8 
2 3 4 5 6 7 8 
2 3 4 5 6 7 8 
2 3 4 …
```
=> Adding an X and Y offset to the current crop effect (large refactor)

src/CVTracker.cpp, tests/CVTracker.cpp
This PR fixes the "SaveLoad_Protobuf" unit test so that it passes with OpenCV 4.5.2+ (where previously it was asserting due to an empty ROI, see linked issue.
Fixes: #686 
cc: @BrennoCaldato
=> Fix CVTracker tests

.github/workflows/ci.yml, CMakeLists.txt
This is an experimental attempt to replace use of the libopenshot-audio PPA with a cached build done during CI. The cache is keyed on the OS, compiler, and a hash of the OpenShotAudio `CMakeLists.txt`; iff all of those are the same, it will skip building the audio lib.
This will allow us to add macOS and Windows CI builds for libopenshot.
=> CI: Build audio lib & cache

src/Timeline.cpp
Reverting the "Adjusting Timeline final_cache to match the video caching thread max_frames, so one doesn't clobber the other." part of a previous commit.
Adjusting the cache size in `SetMaxSize()` ignores OpenShot's cache preferences. This prevents using a cache larger than the preview buffer, which is often a desirable thing. The initial size set for `final_cache` on initialization is merely a starting point, meant to be overridden by OpenShot based on preferences.
This partially reverts commit 0c4e1bcce4d8cbdc1edc752fe3339acf94ac8eb1.
My OpenShot PR OpenShot/openshot-qt#4075 (which I will now close) was based on confusion created by the fallout from this change. (I thought the Timeline cache was removed along with the Clip cache, since it appeared to be non-persistent due to the tiny …
=> Revert final_cache size breakage to unbreak OpenShot caching

bindings/python/openshot.i, src/Exceptions.h
- Most exceptions are now based on one of two new base classes,  FileExceptionBase and FrameExceptionBase. Both inherit from ExceptionBase.
- **All** exception classes derived from ExceptionBase now export a `py_message()` method
(inherited or defined) which constructs a message for Python that includes **all** arguments to the exception, not just the `why()` text.
- Python's exception handling is updated to catch `openshot::ExceptionBase` and display `py_message()` instead of `why()`
- (I didn't modify `why()` because it returns `char*`; `py_message()` returns a `std::string`. `why()` is a `const` method not conducive to constructing and returning a temporary `char*`.)
=> Exceptions: Add py_message() for Python
