OpenShot/libopenshot

tests/tests.cpp
The test programme should exit with a non-zero status if the tests fail.
=> Exit tests with the return value from RunAllTests()

src/bindings/ruby/openshot.i
=> Fix regression caused by f12ffe69

src/TextReader.cpp
This pull request fixes issue: #55 - which is resulting in black frames when trying to create text.
I've resubmitted the PR using a dedicated branch so I can move my own master forward.
Please consider this branch as a fix for creating text, or am I missing something?
=> Allowing TextReader to create text frames using ImageMagick

.gitlab-ci.yml
Small refactor of gitlab ci for libopenshot
=> Refactor of GitLab Ci

.gitlab-ci.yml, include/Timeline.h, src/Frame.cpp, src/Timeline.cpp
Replacing old method with a new method, which calculates the max volume (or all intersecting clips), and scales them all to fit within 100%.
=> New audio mixing code (to prevent exceeding 100%)

src/FFmpegReader.cpp, src/Timeline.cpp
New experimental protections for FFmpegReader::GetFrame, and better frame ordering. Thanks @PeterM!
=> New experimental protections for FFmpegReader::GetFrame

src/effects/Blur.cpp
(cherry picked from commit 9ae61e5)
=> Fix logic for 3 of the 4 blur parameters (#118)

include/Version.h
Reverting version back to release version #
=> Revert: Update Version.h

include/effects/Mask.h, src/FFmpegReader.cpp, src/effects/Mask.cpp
Better support for FPS detection on streaming files and large FPS files. Also adding in new Mask property type (for changing readers), so the user can adjust Transition images or adjust the Mask effect.
=> Improved FPS detection and new Mask Properties

src/FFmpegWriter.cpp
Final frames stored in buffer need to be flushed/drained so that they
can be written to the video file. Credit to Peter for the update.
=> Fix bug with FFmpeg > 3.2 flushing frames

include/ChunkReader.h, include/DecklinkReader.h, include/DummyReader.h, include/FFmpegReader.h, include/FrameMapper.h, include/ImageReader.h, include/Qt/VideoCacheThread.h, include/QtImageReader.h, include/ReaderBase.h, include/TextReader.h, include/Timeline.h, src/CacheMemory.cpp, src/Qt/PlayerPrivate.cpp, src/Qt/VideoCacheThread.cpp, src/Timeline.cpp, tests/ReaderBase_Tests.cpp
**Work in Progress:** Performance improvements to parallel processing for Timeline frames and a new caching approach (using a thread pool).
=> WIP: Performance Improvements to timeline processing and caching thread

.travis.yml, tests/CMakeLists.txt
Experimental fix for libopenshot cmake 3 support
=> Fix cmake 3 error for `make test`

src/KeyFrame.cpp
Further simplify the else branches.
Thanks to SuslikV for pointing this out.
=> Simplification

include/CacheBase.h, include/CacheMemory.h, include/Clip.h, include/ClipBase.h, include/DummyReader.h, include/FFmpegReader.h, include/FFmpegUtilities.h, include/Frame.h, include/FrameMapper.h, include/QtImageReader.h, include/ReaderBase.h, include/Timeline.h, src/CacheBase.cpp, src/Clip.cpp, src/ClipBase.cpp, src/DummyReader.cpp, src/FFmpegReader.cpp, src/FFmpegWriter.cpp, src/Frame.cpp, src/FrameMapper.cpp, src/QtImageReader.cpp, src/ReaderBase.cpp, src/Timeline.cpp, tests/Timeline_Tests.cpp
Thanks to @ckirmse (and @eisneinechse) for the help with identifying memory leaks, adding virtual destructors, testing and fixing some crashes. Original PR: https://github.com/OpenShot/libopenshot/pull/233. As far as I can tell, things seem stable and non-crashy with this branch, and all unit tests work now.
=> Fixing Memory Leaks (lots of them)

src/Clip.cpp, src/Timeline.cpp
@jonoomph let me know if these were implemented somewhere else, but I couldn't find it.
=> make use of crop_x, crop_y, crop_with, crop_height keyframes

doc/HW-ACCEL.md
By using actual Unicode characters for the various ✔️ and ❌ marks in the table, Doxygen will format it properly.
Also:
- Changed to superscripted numerals, for the various callouts
- Reformatted notes into a corresponding ordered list
- Added invisible spaces after the marks without a callout, to balance centering
- Added center-alignment markers to appropriate table columns
=> Update table in HW-ACCEL.md for Doxygen

include/FFmpegUtilities.h
For clear reading of the code on the web.
=> Fix indentation in FFmpegUtilities.h

src/ZmqLogger.cpp
Fixes https://github.com/OpenShot/openshot-qt/issues/2933
=> Disable debug logger on close

src/CMakeLists.txt, tests/CMakeLists.txt
Ugh. My last pull request was a sloppy mess, indentation-wise.
=> Fix my CMakeLists indentation

src/FFmpegReader.cpp
Patch provided by @laochen, reviewed by @eisneinechse 
Fixes #272
=> Add lock to CreateFrame

src/bindings/python/openshot.i, src/bindings/ruby/openshot.i
In adding default arguments to some of our library calls, I unknowingly triggered a somewhat odd SWIG feature, intended for languages that don't support default arguments, where it creates a separate target binding function for _each_ permutation of any source language function which accepts default arguments.
Since Python and Ruby handle default args just fine, we don't need that, and fortunately SWIG provides an easy way to disable it: the [`compactdefaultargs` feature flag](http://www.swig.org/Doc3.0/SWIGDocumentation.html#SWIGPlus_default_args). So, this PR enables that in both interface files.
If nothing else, it cuts down the _documentation_ for the AppendDebug ZMQ method from this:
```
Help on function AppendDebugMethod in openshot.ZmqLogger:
openshot.ZmqLogger.AppendDebugMethod = …
```
=> SWIG: Use compactdefaultargs in bindings

include/KeyFrame.h, src/KeyFrame.cpp, src/Point.cpp
I was need to look at animation keys for some new feature and found that few comments are wrong.
=> Clarify some comments

cmake/Modules/FindRESVG.cmake, src/CMakeLists.txt, tests/CMakeLists.txt
Opened on a project-repo branch, for builder testing. (If it passes I'll throw it to the release branch.)
=> FindRESVG: Modernize with targets

include/TextReader.h
Correcting small documentation error.
=> Documentation error

cmake/Modules/CodeCoverage.cmake
There have been some enhancements made to `CodeCoverage.cmake` in [bilke/cmake-modules](https://github.com/bilke/cmake-modules), incorporating them into our local copy.
=> Update CodeCoverage.cmake module

src/effects/Hue.cpp
Hue was already pretty efficient, but `#pragma omp parallel for` and some streamlining still produced moderate speedups.
* Export rate increased from 6.60 FPS to 12.90 FPS, very nearly twice as fast
* Time to export a 15-second test clip down from 1m 08s to 35s.
=> Hue: Optimize and parallelize

src/effects/Brightness.cpp
As with #423, this streamlines the Brightness code (less severely, as it was already fairly efficient), and adds a `#pragma omp parallel for` decorator to the main `for()` loop so that it will be multi-threaded.
On my 4-core system, a Brightness/Contrast effect on the same 11-second Big Buck Bunny clip exported in 19 seconds, down from 48.
=> Parallelize and streamline Brightness effect

CMakeLists.txt, src/CMakeLists.txt, tests/CMakeLists.txt
Preparing for upcoming release, bumping versions and dependencies.
=> Bump version to 0.2.5-dev1 (and libopenshot-audio dependency to 0.2.0)

src/FFmpegReader.cpp, src/FFmpegWriter.cpp, src/FrameMapper.cpp, tests/FFmpegReader_Tests.cpp
Fixes: https://github.com/OpenShot/libopenshot/issues/456
=> Fix distortion during mix of audio

.github/stale.yml
I give full credit to the GitLab-CE project for some of this wording. It was so artfully said, I adapted a version for OpenShot. Not sure how to give proper credit, so hopefully this works.
=> Update the stale github message (libopenshot)

.github/workflows/label-merge-conflicts.yml
Now that I've gotten this worked out in the openshot-qt repo, it'll be useful here as well.
=> Add label-merge-conflicts Action workflow

.github/dependabot.yml
Same as OpenShot/openshot-qt#3935
=> Add Dependabot checking for Actions

tests/DummyReader_Tests.cpp
This adds tests to bring coverage of `DummyReader.h` to 100%, and coverage of `DummyReader.cpp` to nearly the same level. The only gaps should be some difficult-to-reach (if not outright impossible) exception-throwing paths.
=> tests/DummyReader: Goose coverage

doc/INSTALL-MAC.md
Found it to be a problem while setting up.
=> fix cmake instructions using '-d' argument in MacOs
